In [1]:
import pandas as pd

# este es el csv de 464 registros
df = pd.read_csv("../data/coches_segunda_mano-19-02-2025.csv")
df

,marca,anio,localizacion,kilometraje,combustible,distintivo_ambiental,garantia,cambio,carroceria,plazas,...,puertas,color,precio,vendedor,consumo_medio,certificado,fecha_extraccion,referencia,url,ruta_imagen
0,PEUGEOT 308 1.4 95cv 5p.,05/2009,Lleida,142.137 km,Gasolina,C,12 meses,Manual,Berlina mediana o grande,NaN,...,5 Puertas,Gris,7.900 €\n13%\n6.900 €,ASTER AUTOS\nProfesional,NaN,No,2025-02-19 17:01:36.887580,ref14946771,https://www.autocasion.com/coches-segunda-mano...,../img/coches/14946771-0-5926368496749e1fa4cfb...
1,SEAT León ST 1.6 TDI CR 85 kW (115 CV) Start&S...,06/2020,Lleida,106.736 km,Diésel,NaN,12 meses,Manual,Familiar,NaN,...,5 Puertas,Blanco,13.500 €,ASTER AUTOS\nProfesional,NaN,No,2025-02-19 17:01:44.312012,ref14962083,https://www.autocasion.com/coches-segunda-mano...,../img/coches/14962083-0-824922025674e0c07cb9c...
2,PEUGEOT 308 1.5BlueHDi S&S Style 130,09/2019,Lleida,68.314 km,Diesel,C,12 meses,Manual,Berlina,5 asientos,...,5 Puertas,Gris,13.900 €,ASTER AUTOS\nProfesional,"Consumo medio\n3,60\nlitros/100 km",No,2025-02-19 17:01:54.282640,ref15014897,https://www.autocasion.com/coches-segunda-mano...,../img/coches/15014897-0-1402892972675898157d3...
3,OPEL Grandland X Grand Land 1.6CDTI Selective,10/2018,Lleida,55.531 km,Diésel,NaN,12 meses,Manual,"4x4, SUV o pickup",NaN,...,5 Puertas,Gris,17.950 €,ASTER AUTOS\nProfesional,NaN,No,2025-02-19 17:02:02.672957,ref15027844,https://www.autocasion.com/coches-segunda-mano...,../img/coches/15027844-0-557393874675b05f31fab...
4,AUDI A3 Sportback Sportback 35 TFSI 150cv,02/2021,Lleida,75.800 km,Gasolina,C,12 meses,Manual,Berlina mediana o grande,NaN,...,5 Puertas,Azul,24.900 €,ASTER AUTOS\nProfesional,NaN,No,2025-02-19 17:02:11.380113,ref15068938,https://www.autocasion.com/coches-segunda-mano...,../img/coches/15068938-0-21278795586762f4e3501...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7899,AUDI Q2 30 TFSI Advanced 81kW,06/2023,Madrid,5.000 km,Gasolina,C,24 meses,Manual,Todo Terreno,5 asientos,...,5 Puertas,Blanco,31.750 €,F. Tomé\nProfesional,"Consumo medio\n0,00\nlitros/100 km",No,2025-02-20 16:58:24.429571,ref11514960,https://www.autocasion.com/coches-km0/km-0/aud...,../img/coches/c6a7d66fca06e1fe30a217bb4e369737...
7900,VOLKSWAGEN T-Cross 1.0 TSI Life 85kW Aut.,04/2024,Madrid,4.409 km,Gasolina,C,12 meses,Automático,Todo Terreno,5 asientos,...,5 Puertas,Azul / Metalizado,24.750 €,F. Tomé\nProfesional,"Consumo medio\n0,00\nlitros/100 km",No,2025-02-20 16:58:33.963944,ref15131848,https://www.autocasion.com/coches-km0/km-0/vol...,../img/coches/15131848-0-4250565599676fa98417e...
7901,VOLKSWAGEN T-Cross 1.0 TSI Advance,06/2022,Madrid,32.034 km,Gasolina,C,12 meses,Manual,Todo Terreno,5 asientos,...,5 Puertas,Gris / Metalizado,18.350 €,F. Tomé\nProfesional,"Consumo medio\n0,00\nlitros/100 km",No,2025-02-20 16:58:43.012147,ref14321102,https://www.autocasion.com/coches-segunda-mano...,../img/coches/14321102-0-348538236466e52fccc0d...
7902,VOLKSWAGEN Touran 2.0TDI Life DSG7 110kW,12/2024,Madrid,5.000 km,Diesel,C,12 meses,Automático,Monovolumen,7 asientos,...,5 Puertas,Blanco,43.750 €,F. Tomé\nProfesional,"Consumo medio\n0,00\nlitros/100 km",No,2025-02-20 16:58:50.765870,ref15414020,https://www.autocasion.com/coches-km0/km-0/vol...,../img/coches/15414020-0-232832890567acf283acf...
7903,VOLKSWAGEN Taigo 1.0 TSI Life 81kW,03/2024,Madrid,5.000 km,Gasolina,C,12 meses,Manual,Todo Terreno,5 asientos,...,5 Puertas,Negro,26.750 €,F. Tomé\nProfesional,"Consumo medio\n0,00\nlitros/100 km",No,2025-02-20 16:59:00.820588,ref12854839,https://www.autocasion.com/coches-km0/km-0/vol...,../img/coches/12854839-0-428134073166229674269...

In [2]:
df_conces = pd.read_csv("../data/concesionarios.csv")
df_conces

,nombre,calle,municipio,provincia,codigo_postal
0,--AUTOMOVILES VIA NORTE --,Calle: C/ Rosalia De Castro 7 - 9,Municipio: Naron,Provincia: La coruña,Código postal: 15570
1,*ACS MOTOR*,"Calle: Carretera Villanueva De La Jara, 25",Municipio: Iniesta,Provincia: Cuenca,Código postal: 16235
2,+ QUE COCHES,Calle: Avda Pio Xii 85,Municipio: Talavera de la reina,Provincia: Toledo,Código postal: 45600
3,11ELEVEN,Calle: Concertar Cita Previa,Municipio: Madrid,Provincia: Madrid,Código postal: 28294
4,13 Premium Cars,"Calle: Cars Carrer Benito Pérez Galdós, 27,",Municipio: Aldaia,Provincia: Valencia,Código postal: 46960
...,...,...,...,...,...
4076,ZENCARS,Calle: Atendemos Con Cita Previa.,Municipio: Madrid,Provincia: Madrid,Código postal: 28049
4077,"ZENTRO MACHINE- CASE, S.A.",NaN,NaN,Provincia: Madrid,NaN
4078,ZOANSA TAILERRAK,"Calle: Pol. Ind. Alkaiaga, C. Banarta, 2,","Municipio: Lesaka, navarra",Provincia: Navarra,Código postal: 31770
4079,ZOE AUTOMOCION,Calle: Calle Greco S/N,Municipio: Sonseca,Provincia: Toledo,Código postal: 45100
4080,Zylautos Motor,"Calle: V Real De Madrid 129,",Municipio: Valencia,Provincia: Valencia,Código postal: 46017

In [3]:
df_conces.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4081 entries, 0 to 4080
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   nombre         4081 non-null   object
 1   calle          3879 non-null   object
 2   municipio      3879 non-null   object
 3   provincia      4078 non-null   object
 4   codigo_postal  3879 non-null   object
dtypes: object(5)
memory usage: 159.5+ KB

In [4]:
# Obtener la longitud de cada cadena
longitudes = df_conces[~df_conces["calle"].isna()]["calle"].apply(len)

# Obtener la longitud máxima
longitud_maxima = longitudes.max()

longitud_maxima

np.int64(91)

In [5]:
df["consumo_medio"].unique()

array([nan, 'Consumo medio\n3,60\nlitros/100 km',
       'Consumo medio\n4,90\nlitros/100 km',
       'Consumo medio\n5,10\nlitros/100 km',
       'Consumo medio\n5,60\nlitros/100 km',
       'Consumo medio\n3,90\nlitros/100 km',
       'Consumo medio\n4,40\nlitros/100 km',
       'Consumo medio\n7,40\nlitros/100 km',
       'Consumo medio\n9,10\nlitros/100 km',
       'Consumo medio\n5,20\nlitros/100 km',
       'Consumo medio\n3,20\nlitros/100 km',
       'Consumo medio\n8,40\nlitros/100 km',
       'Consumo medio\nlitros/100 km',
       'Consumo medio\n4,00\nlitros/100 km',
       'Consumo medio\n7,50\nlitros/100 km',
       'Consumo medio\n4,80\nlitros/100 km',
       'Consumo medio\n3,70\nlitros/100 km',
       'Consumo medio\n3,80\nlitros/100 km',
       'Consumo medio\n0,00\nlitros/100 km',
       'Consumo medio\n12,10\nlitros/100 km',
       'Consumo medio\n4,60\nlitros/100 km',
       'Consumo medio\n6,30\nlitros/100 km',
       'Consumo medio\n1,70\nlitros/100 km',
       'Consumo medio\n4,20\nlitros/100 km',
       'Consumo medio\n6,00\nlitros/100 km',
       'Consumo medio\n1,40\nlitros/100 km',
       'Consumo medio\n1,90\nlitros/100 km',
       'Consumo medio\n5,80\nlitros/100 km',
       'Consumo medio\n5,00\nlitros/100 km',
       'Consumo medio\n10,40\nlitros/100 km',
       'Consumo medio\n7,20\nlitros/100 km',
       'Consumo medio\n6,40\nlitros/100 km',
       'Consumo medio\n5,30\nlitros/100 km',
       'Consumo medio\n5,70\nlitros/100 km',
       'Consumo medio\n6,60\nlitros/100 km',
       'Consumo medio\n8,10\nlitros/100 km',
       'Consumo medio\n4,70\nlitros/100 km',
       'Consumo medio\n5,40\nlitros/100 km',
       'Consumo medio\n4,30\nlitros/100 km',
       'Consumo medio\n3,50\nlitros/100 km',
       'Consumo medio\n6,10\nlitros/100 km',
       'Consumo medio\n6,50\nlitros/100 km',
       'Consumo medio\n9,60\nlitros/100 km',
       'Consumo medio\n10,50\nlitros/100 km',
       'Consumo medio\n8,00\nlitros/100 km',
       'Consumo medio\n11,80\nlitros/100 km',
       'Consumo medio\n6,80\nlitros/100 km',
       'Consumo medio\n7,00\nlitros/100 km',
       'Consumo medio\n9,30\nlitros/100 km',
       'Consumo medio\n8,60\nlitros/100 km',
       'Consumo medio\n4,50\nlitros/100 km',
       'Consumo medio\n3,30\nlitros/100 km',
       'Consumo medio\n5,90\nlitros/100 km',
       'Consumo medio\n6,70\nlitros/100 km',
       'Consumo medio\n4,10\nlitros/100 km',
       'Consumo medio\n7,30\nlitros/100 km',
       'Consumo medio\n11,10\nlitros/100 km',
       'Consumo medio\n8,80\nlitros/100 km',
       'Consumo medio\n7,10\nlitros/100 km',
       'Consumo medio\n7,90\nlitros/100 km',
       'Consumo medio\n7,60\nlitros/100 km',
       'Consumo medio\n6,90\nlitros/100 km',
       'Consumo medio\n5,50\nlitros/100 km',
       'Consumo medio\n2,50\nlitros/100 km',
       'Consumo medio\n1,80\nlitros/100 km',
       'Consumo medio\n9,40\nlitros/100 km',
       'Consumo medio\n2,20\nlitros/100 km',
       'Consumo medio\n6,20\nlitros/100 km',
       'Consumo medio\n11,40\nlitros/100 km',
       'Consumo medio\n16,20\nlitros/100 km',
       'Consumo medio\n3,40\nlitros/100 km',
       'Consumo medio\n20,50\nlitros/100 km',
       'Consumo medio\n13,10\nlitros/100 km',
       'Consumo medio\n9,20\nlitros/100 km',
       'Consumo medio\n8,20\nlitros/100 km',
       'Consumo medio\n12,70\nlitros/100 km',
       'Consumo medio\n11,30\nlitros/100 km',
       'Consumo medio\n7,70\nlitros/100 km',
       'Consumo medio\n9,50\nlitros/100 km',
       'Consumo medio\n10,80\nlitros/100 km',
       'Consumo medio\n9,90\nlitros/100 km',
       'Consumo medio\n13,20\nlitros/100 km',
       'Consumo medio\n2,00\nlitros/100 km',
       'Consumo medio\n1,60\nlitros/100 km',
       'Consumo medio\n8,70\nlitros/100 km',
       'Consumo medio\n9,00\nlitros/100 km',
       'Consumo medio\n2,80\nlitros/100 km',
       'Consumo medio\n7,80\nlitros/100 km',
       'Consumo medio\n11,50\nlitros/100 km',
       'Consumo medio\n11,00\nlitros/100 km',
       'Consumo medio\n12,50\nlitros/100 km',
       'Consumo medio\n16,00\nlitros/100 km',
       'Consumo medio\n3,10\nlitros/100 km',
       'Consumo medio\n10,30\nlitros/100 km',
       'Consumo medio\n9,80\nlitros/100 km',
       'Consumo medio\n8,30\nlitros/100 km',
       'Consumo medio\n8,90\nlitros/100 km',
       'Consumo medio\n11,60\nlitros/100 km',
       'Consumo medio\n2,70\nlitros/100 km',
       'Consumo medio\n2,10\nlitros/100 km',
       'Consumo medio\n1,20\nlitros/100 km',
       'Consumo medio\n10,90\nlitros/100 km',
       'Consumo medio\n12,80\nlitros/100 km',
       'Consumo medio\n2,60\nlitros/100 km',
       'Consumo medio\n13,80\nlitros/100 km'], dtype=object)

In [6]:
import sys
import os

notebook_path = os.path.abspath(".")
sys.path.append(os.path.abspath(os.path.join(notebook_path, '..', 'src')))

from limpieza import limpia

df_limpio = limpia.limpiar_csv("../data/coches_segunda_mano-19-02-2025.csv")

In [7]:
df_limpio

,modelo_titulo,provincia,kilometraje,combustible,distintivo_ambiental,garantia,cambio_automatico,carroceria,plazas,potencia,...,fecha_extraccion,referencia,url,ruta_imagen,marca_sola,mes_matricula,anio_matricula,nombre_vendedor_profesional,peninsula_y_baleares,comunidad
0,308 1.4 95cv 5p.,Lleida,142137,Gasolina,C,12.0,False,Berlina,NaN,95.0,...,2025-02-19 17:01:36.887580,14946771,https://www.autocasion.com/coches-segunda-mano...,../img/coches/14946771-0-5926368496749e1fa4cfb...,PEUGEOT,5,2009,ASTER AUTOS,True,Cataluña
1,León ST 1.6 TDI CR 85 kW (115 CV) Start&Stop S...,Lleida,106736,Diésel,NaN,12.0,False,Familiar,NaN,116.0,...,2025-02-19 17:01:44.312012,14962083,https://www.autocasion.com/coches-segunda-mano...,../img/coches/14962083-0-824922025674e0c07cb9c...,SEAT,6,2020,ASTER AUTOS,True,Cataluña
2,308 1.5BlueHDi S&S Style 130,Lleida,68314,Diésel,C,12.0,False,Berlina,5.0,130.0,...,2025-02-19 17:01:54.282640,15014897,https://www.autocasion.com/coches-segunda-mano...,../img/coches/15014897-0-1402892972675898157d3...,PEUGEOT,9,2019,ASTER AUTOS,True,Cataluña
3,Grandland X Grand Land 1.6CDTI Selective,Lleida,55531,Diésel,NaN,12.0,False,"4x4, SUV o pickup",NaN,120.0,...,2025-02-19 17:02:02.672957,15027844,https://www.autocasion.com/coches-segunda-mano...,../img/coches/15027844-0-557393874675b05f31fab...,OPEL,10,2018,ASTER AUTOS,True,Cataluña
4,A3 Sportback Sportback 35 TFSI 150cv,Lleida,75800,Gasolina,C,12.0,False,Berlina,NaN,150.0,...,2025-02-19 17:02:11.380113,15068938,https://www.autocasion.com/coches-segunda-mano...,../img/coches/15068938-0-21278795586762f4e3501...,AUDI,2,2021,ASTER AUTOS,True,Cataluña
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7847,Q2 ADVANCED 30 TFSI 81(110) KW(CV) 6 VEL.,Murcia,56640,Gasolina,C,12.0,False,"4x4, SUV o pickup",NaN,110.0,...,2025-02-20 16:50:19.841595,15333890,https://www.autocasion.com/coches-segunda-mano...,../img/coches/91c126beae1477982e79150aa72153fc...,AUDI,2,2021,AUDI HUERTAS MOTOR MURCIA,True,Región de Murcia
7848,Golf 2.0TDI Sport DSG7 110kW,Madrid,42000,Diésel,C,12.0,True,Berlina,5.0,150.0,...,2025-02-20 16:50:28.065854,15450596,https://www.autocasion.com/coches-segunda-mano...,../img/coches/1798790e897d8cfc4f01c5e9c342acfb...,VOLKSWAGEN,11,2020,Matexcar,True,Comunidad de Madrid
7849,A6 Avant 40 TDI S tronic,Murcia,24304,Diésel,ECO,12.0,True,Familiar,5.0,204.0,...,2025-02-20 16:50:37.503167,15333884,https://www.autocasion.com/coches-segunda-mano...,../img/coches/ec0183657d36a2c20336c8656afc507c...,AUDI,4,2023,AUDI HUERTAS MOTOR MURCIA,True,Región de Murcia
7902,Touran 2.0TDI Life DSG7 110kW,Madrid,5000,Diésel,C,12.0,True,Monovolumen,7.0,150.0,...,2025-02-20 16:58:50.765870,15414020,https://www.autocasion.com/coches-km0/km-0/vol...,../img/coches/15414020-0-232832890567acf283acf...,VOLKSWAGEN,12,2024,F. Tomé,True,Comunidad de Madrid
7903,Taigo 1.0 TSI Life 81kW,Madrid,5000,Gasolina,C,12.0,False,Todo Terreno,5.0,110.0,...,2025-02-20 16:59:00.820588,12854839,https://www.autocasion.com/coches-km0/km-0/vol...,../img/coches/12854839-0-428134073166229674269...,VOLKSWAGEN,3,2024,F. Tomé,True,Comunidad de Madrid

In [8]:
df_limpio.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4778 entries, 0 to 7903
Data columns (total 26 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   modelo_titulo                4778 non-null   object
 1   provincia                    4778 non-null   object
 2   kilometraje                  4778 non-null   object
 3   combustible                  4751 non-null   object
 4   distintivo_ambiental         4377 non-null   object
 5   garantia                     4778 non-null   float64
 6   cambio_automatico            4778 non-null   bool
 7   carroceria                   4774 non-null   object
 8   plazas                       3241 non-null   float64
 9   potencia                     4753 non-null   float64
 10  puertas                      4778 non-null   int64
 11  color                        4778 non-null   object
 12  precio                       4777 non-null   float64
 13  vendedor_profesional         4778 non-null   bool
 14  consumo_medio                3039 non-null   float64
 15  certificado                  4778 non-null   bool
 16  fecha_extraccion             4778 non-null   datetime64[ns]
 17  referencia                   4778 non-null   int64
 18  url                          4778 non-null   object
 19  ruta_imagen                  4769 non-null   object
 20  marca_sola                   4778 non-null   object
 21  mes_matricula                4778 non-null   int64
 22  anio_matricula               4778 non-null   int64
 23  nombre_vendedor_profesional  4776 non-null   string
 24  peninsula_y_baleares         4778 non-null   bool
 25  comunidad                    4628 non-null   object
dtypes: bool(4), datetime64[ns](1), float64(5), int64(4), object(11), string(1)
memory usage: 877.2+ KB

In [9]:
df_limpio["consumo_medio"].isna().sum()

np.int64(1739)

In [16]:
df_limpio["consumo_medio"].unique()

array([ nan,  3.6,  4.9,  5.1,  5.6,  3.9,  4.4,  7.4,  9.1,  5.2,  3.2,
        8.4,  4. ,  7.5,  4.8,  3.7,  3.8,  0. , 12.1,  4.6,  6.3,  1.7,
        4.2,  6. ,  1.4,  1.9,  5.8,  5. , 10.4,  7.2,  6.4,  5.3,  5.7,
        6.6,  8.1,  4.7,  5.4,  4.3,  3.5,  6.1,  6.5,  9.6, 10.5,  8. ,
       11.8,  6.8,  7. ,  9.3,  8.6,  4.5,  3.3,  5.9,  6.7,  4.1,  7.3,
       11.1,  8.8,  7.1,  7.9,  7.6,  6.9,  5.5,  2.5,  1.8,  9.4,  2.2,
        6.2, 11.4, 16.2,  3.4, 20.5, 13.1,  9.2,  8.2, 12.7, 11.3,  7.7,
        9.5, 10.8,  9.9, 13.2,  2. ,  1.6,  8.7,  9. ,  2.8,  7.8, 11.5,
       11. , 12.5, 16. ,  3.1, 10.3,  9.8,  8.3,  8.9, 11.6,  2.7,  2.1,
        1.2, 10.9, 12.8,  2.6, 13.8])

In [10]:
urls_imagenes = df_limpio["ruta_imagen"].unique().tolist()

In [11]:
# Obtener la longitud de cada cadena en la columna "url"
longitudes = df_limpio[~df_limpio["ruta_imagen"].isna()]["ruta_imagen"].apply(len)

# Obtener la longitud máxima
longitud_maxima = longitudes.max()

longitud_maxima

np.int64(63)

In [12]:
len(urls_imagenes[129])

63

In [13]:
df_limpio[df_limpio["comunidad"].isna()]

,modelo_titulo,provincia,kilometraje,combustible,distintivo_ambiental,garantia,cambio_automatico,carroceria,plazas,potencia,...,fecha_extraccion,referencia,url,ruta_imagen,marca_sola,mes_matricula,anio_matricula,nombre_vendedor_profesional,peninsula_y_baleares,comunidad
48,Clase C Estate 300 e 9G-Tronic,Tenerife,26200,Híbrido Enchufable,0 EMISIONES,12.0,True,Familiar,5.0,320.0,...,2025-02-19 17:09:45.113796,15036613,https://www.autocasion.com/coches-segunda-mano...,../img/coches/5ac51b315436aa58abd0f1381eba01b4...,MERCEDES-BENZ,1,2020,RS MOTOR'S,False,NaN
66,Coupé Deportivo Automático de 3 Puertas,Tenerife,83800,Gasolina,B,12.0,True,Deportivo o coupé,4.0,390.0,...,2025-02-19 17:12:48.718504,15453224,https://www.autocasion.com/coches-segunda-mano...,../img/coches/1fa0734b6727ded3fa710d65336bea6d...,MASERATI,8,2003,PUNTOMOTOR TENERIFE,False,NaN
69,C4 Familiar Manual de 5 Puertas,Tenerife,129000,Diésel,NaN,12.0,False,Familiar,7.0,115.0,...,2025-02-19 17:13:14.349037,15177570,https://www.autocasion.com/coches-segunda-mano...,../img/coches/388afd893d5e63714191bb68a9ba82d0...,CITROEN,5,2016,PUNTOMOTOR TENERIFE,False,NaN
291,Kamiq 1.0 TSI Monte Carlo 85kW DSG7,Tenerife,3858,Gasolina,C,12.0,True,Todo Terreno,5.0,115.0,...,2025-02-19 17:51:09.242657,13389661,https://www.autocasion.com/coches-km0/km-0/sko...,../img/coches/13389661-0-19157314586669eb66655...,SKODA,3,2024,CONCESIONARIO ANGEL BELLO,False,NaN
292,Tiguan 1.5 TSI 96kW,Tenerife,40299,Gasolina,C,12.0,False,Todo Terreno,5.0,130.0,...,2025-02-19 17:51:18.671926,14754451,https://www.autocasion.com/coches-segunda-mano...,../img/coches/14754451-0-3542032014672bac3e578...,VOLKSWAGEN,7,2021,CONCESIONARIO ANGEL BELLO,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6678,i3 120Ah,Islas Baleares,97088,Eléctrico,0 EMISIONES,12.0,True,Monovolumen,4.0,170.0,...,2025-02-20 13:14:34.456433,14000321,https://www.autocasion.com/coches-segunda-mano...,../img/coches/53de05f310cfe0da644db9bd4603eedc...,BMW,5,2019,PROA OCASION IBIZA,True,NaN
6679,Ceed 1.6 GDI PHEV EMOTION TOURER 141 5P,Islas Baleares,28170,Híbrido Enchufable,0 EMISIONES,12.0,True,Familiar,NaN,141.0,...,2025-02-20 13:14:41.316382,14965265,https://www.autocasion.com/coches-segunda-mano...,../img/coches/8b32b52105625f362b350f396d0816da...,KIA,12,2021,PROA OCASION IBIZA,True,NaN
6681,Vitara 1.5 HEV GLE STRONG AUTO 116 5P,Islas Baleares,34622,Gasolina,C,12.0,True,"4x4, SUV o pickup",NaN,116.0,...,2025-02-20 13:14:57.634102,15348450,https://www.autocasion.com/coches-segunda-mano...,../img/coches/72046c1ba06e331a819467c3a44fca01...,SUZUKI,6,2022,PROA OCASION IBIZA,True,NaN
6682,Ceed 1.6 GDI PHEV ETECH TOURER 141 5P,Islas Baleares,20139,Híbrido Enchufable,0 EMISIONES,12.0,True,Familiar,NaN,141.0,...,2025-02-20 13:15:06.122132,15348445,https://www.autocasion.com/coches-segunda-mano...,../img/coches/838666a5ba19f36c7bdfd4d789628c03...,KIA,12,2021,PROA OCASION IBIZA,True,NaN
6683,Q3 1.5 35 TFSI S TRONIC BLACK LINE 150 5P,Islas Baleares,26565,Gasolina,C,12.0,True,"4x4, SUV o pickup",NaN,150.0,...,2025-02-20 13:15:14.242140,15424767,https://www.autocasion.com/coches-segunda-mano...,../img/coches/b4f97b97f378d47c38d7c050548ac4bc...,AUDI,9,2022,PROA OCASION IBIZA,True,NaN

In [14]:
longitudes = df_limpio["nombre_vendedor_profesional"].apply(lambda x: len(x) if pd.notna(x) else 0)


# Obtener la longitud máxima
longitud_maxima = longitudes.max()

longitud_maxima

np.int64(50)

In [15]:
# con esto sabréis la ruta actual

import os

ruta_actual = os.getcwd()

print(f"La ruta actual de trabajo es: {ruta_actual}")

La ruta actual de trabajo es: /home/bross/Codigo_HAB/PFB_coches/PFB_coches/temp