In [1]:
import pandas as pd

# este es el csv de 464 registros
df = pd.read_csv("../data/coches_segunda_mano-18-02-2025.csv")
df

,marca,anio,localizacion,kilometraje,combustible,distintivo_ambiental,garantia,cambio,carroceria,plazas,potencia,puertas,color,precio,vendedor,consumo_medio,certificado,fecha_extraccion,referencia
0,FORD Mustang 5.0 Ti-VCT V8+714 CV+RECARO+KAMER...,06/2019,Madrid,23.000 km,Gasolina,C,12 meses,Automático,Pequeño,NaN,714 cv,3 Puertas,gris / Metalizado,64.900 €,GERMACARS MOBILITY\nProfesional,NaN,No,2025-02-18 11:15:17.922326,ref15231216
1,FORD Mustang 5.0 Ti-VCT V8 GT350 LOOK Shelby,01/2019,Madrid,41.000 km,Gasolina,C,12 meses,Manual,Pequeño,NaN,450 cv,3 Puertas,negro / Metalizado,43.000 €,GERMACARS MOBILITY\nProfesional,NaN,No,2025-02-18 11:15:45.618010,ref15221898
2,FORD Focus 2.3 Ecoboost ST 3,12/2020,Madrid,89.552 km,Gasolina,C,12 meses,Manual,Berlina,5 asientos,280 cv,5 Puertas,negro / Metalizado,29.690 €,GERMACARS MOBILITY\nProfesional,"Consumo medio\n7,60\nlitros/100 km",No,2025-02-18 11:15:53.589509,ref15036704
3,BMW X4 xDrive 20dA xLine,04/2024,Granada,25.600 km,Diesel,ECO,24 meses,Automático,Coupe,5 asientos,190 cv,5 Puertas,Azul,57.900 €,FRAMACAR AUTOMOVILES\nProfesional,"Consumo medio\n0,00\nlitros/100 km",No,2025-02-18 11:16:00.414864,ref15227266
4,BMW X4 xDrive 20dA,02/2020,Granada,95.800 km,Diesel,C,12 meses,Automático,Coupe,5 asientos,190 cv,5 Puertas,Rojo,39.490 €,FRAMACAR AUTOMOVILES\nProfesional,"Consumo medio\n5,00\nlitros/100 km",No,2025-02-18 11:16:07.869053,ref15304683
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
459,RENAULT Clio Blue dCi Business 74kW,12/2021,Málaga,54.000 km,Diesel,C,12 meses,Manual,Berlina,5 asientos,100 cv,5 Puertas,Blanco,15.800 €,MARTINSA MOTOR\nProfesional,"Consumo medio\n0,00\nlitros/100 km",Si,2025-02-18 12:17:32.250314,ref15319497
460,RENAULT Mégane 1.5dCi Blue Life 85kW,12/2021,Málaga,47.000 km,Diesel,C,12 meses,Manual,Berlina,5 asientos,115 cv,5 Puertas,Blanco,17.800 €,MARTINSA MOTOR\nProfesional,"Consumo medio\n3,90\nlitros/100 km",Si,2025-02-18 12:17:37.597308,ref15318805
461,VOLKSWAGEN Polo 1.0 TSI R-Line 70kW,12/2021,Málaga,21.000 km,Gasolina,C,12 meses,Manual,Berlina,5 asientos,95 cv,5 Puertas,Blanco,19.300 €,MARTINSA MOTOR\nProfesional,"Consumo medio\n0,00\nlitros/100 km",Si,2025-02-18 12:17:43.644339,ref15318499
462,BMW Serie 3 318dA M Sport,05/2024,Málaga,13.000 km,Diesel,ECO,24 meses,Automático,Berlina,5 asientos,150 cv,4 Puertas,Gris,42.300 €,MARTINSA MOTOR\nProfesional,"Consumo medio\n0,00\nlitros/100 km",Si,2025-02-18 12:17:50.859351,ref15303542
463,BMW Serie 1 116d,03/2019,Málaga,52.000 km,Diesel,C,12 meses,Manual,Berlina,5 asientos,116 cv,5 Puertas,Blanco,19.300 €,MARTINSA MOTOR\nProfesional,"Consumo medio\n3,80\nlitros/100 km",Si,2025-02-18 12:17:57.066789,ref15303360

In [8]:
df[df["localizacion"].isna()]

,marca,anio,localizacion,kilometraje,combustible,distintivo_ambiental,garantia,cambio,carroceria,plazas,potencia,puertas,color,precio,vendedor,consumo_medio,certificado,fecha_extraccion,referencia
371,MERCEDES-BENZ Clase V EQV 300 Larga e100,04/2022,NaN,8.540 km,Eléctrico,0 EMISIONES,Sí,Automático,Pequeño,NaN,204 cv,5 Puertas,gris selenita metalizado,49.900 €,MERCEDES CANARIAS LAS PALMAS\nProfesional,NaN,Si,2025-02-18 12:05:16.733564,ref13800403
372,MERCEDES-BENZ EQB 250,07/2023,NaN,14.720 km,Corriente eléctrica,0 EMISIONES,36 meses,Automático,Todo Terreno,5 asientos,190 cv,5 Puertas,Gris montaña metalizado,39.990 €,MERCEDES CANARIAS LAS PALMAS\nProfesional,"Consumo medio\n0,00\nlitros/100 km",Si,2025-02-18 12:05:24.177183,ref14777875
381,NISSAN Juke 1.6 Acenta 4x2 112,02/2019,NaN,90.336 km,Gasolina,C,12 meses,Manual,Todo Terreno,5 asientos,112 cv,5 Puertas,Blanco,13.790 €,SHOPING CAR\nProfesional,"Consumo medio\n6,90\nlitros/100 km",No,2025-02-18 12:06:20.489508,ref15401172

In [9]:
df["localizacion"].unique()

array(['Madrid', 'Granada', 'Vizcaya', 'Málaga', 'Barcelona', 'Sevilla',
       'Girona', 'Alicante', 'Cádiz', 'Zaragoza', 'Ávila', 'Navarra',
       'Toledo', 'Valencia', 'Lugo', 'La Rioja', 'Murcia', 'Badajoz',
       'León', 'Segovia', 'Zamora', nan, 'La Coruña', 'Tarragona',
       'Albacete', 'Castellón', 'Valladolid'], dtype=object)

In [2]:
import sys
import os

notebook_path = os.path.abspath(".")
sys.path.append(os.path.abspath(os.path.join(notebook_path, '..', 'src')))

from limpieza import limpia

df_limpio = limpia.limpiar_csv("../data/coches_segunda_mano-18-02-2025.csv")

In [3]:
df_limpio

,modelo_titulo,provincia,kilometraje,combustible,distintivo_ambiental,garantia,cambio_automatico,carroceria,plazas,potencia,...,consumo_medio,certificado,fecha_extraccion,referencia,marca_sola,mes_matricula,anio_matricula,nombre_vendedor_profesional,peninsula_y_baleares,comunidad
0,Mustang 5.0 Ti-VCT V8+714 CV+RECARO+KAMERA+LED+,Madrid,23000,Gasolina,C,12.0,True,Pequeño,NaN,714.0,...,NaN,False,2025-02-18 11:15:17.922326,15231216,FORD,6,2019,GERMACARS MOBILITY,True,Comunidad de Madrid
1,Mustang 5.0 Ti-VCT V8 GT350 LOOK Shelby,Madrid,41000,Gasolina,C,12.0,False,Pequeño,NaN,450.0,...,NaN,False,2025-02-18 11:15:45.618010,15221898,FORD,1,2019,GERMACARS MOBILITY,True,Comunidad de Madrid
2,Focus 2.3 Ecoboost ST 3,Madrid,89552,Gasolina,C,12.0,False,Berlina,5.0,280.0,...,7.6,False,2025-02-18 11:15:53.589509,15036704,FORD,12,2020,GERMACARS MOBILITY,True,Comunidad de Madrid
3,X4 xDrive 20dA xLine,Granada,25600,Diésel,ECO,24.0,True,Coupe,5.0,190.0,...,NaN,False,2025-02-18 11:16:00.414864,15227266,BMW,4,2024,FRAMACAR AUTOMOVILES,True,Andalucía
4,X4 xDrive 20dA,Granada,95800,Diésel,C,12.0,True,Coupe,5.0,190.0,...,5.0,False,2025-02-18 11:16:07.869053,15304683,BMW,2,2020,FRAMACAR AUTOMOVILES,True,Andalucía
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
459,Clio Blue dCi Business 74kW,Málaga,54000,Diésel,C,12.0,False,Berlina,5.0,100.0,...,NaN,True,2025-02-18 12:17:32.250314,15319497,RENAULT,12,2021,MARTINSA MOTOR,True,Andalucía
460,Mégane 1.5dCi Blue Life 85kW,Málaga,47000,Diésel,C,12.0,False,Berlina,5.0,115.0,...,3.9,True,2025-02-18 12:17:37.597308,15318805,RENAULT,12,2021,MARTINSA MOTOR,True,Andalucía
461,Polo 1.0 TSI R-Line 70kW,Málaga,21000,Gasolina,C,12.0,False,Berlina,5.0,95.0,...,NaN,True,2025-02-18 12:17:43.644339,15318499,VOLKSWAGEN,12,2021,MARTINSA MOTOR,True,Andalucía
462,Serie 3 318dA M Sport,Málaga,13000,Diésel,ECO,24.0,True,Berlina,5.0,150.0,...,NaN,True,2025-02-18 12:17:50.859351,15303542,BMW,5,2024,MARTINSA MOTOR,True,Andalucía
463,Serie 1 116d,Málaga,52000,Diésel,C,12.0,False,Berlina,5.0,116.0,...,3.8,True,2025-02-18 12:17:57.066789,15303360,BMW,3,2019,MARTINSA MOTOR,True,Andalucía

In [4]:
df_limpio.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 464 entries, 0 to 463
Data columns (total 24 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   modelo_titulo                464 non-null    object
 1   provincia                    461 non-null    object
 2   kilometraje                  464 non-null    object
 3   combustible                  464 non-null    object
 4   distintivo_ambiental         441 non-null    object
 5   garantia                     464 non-null    float64
 6   cambio_automatico            464 non-null    bool
 7   carroceria                   462 non-null    object
 8   plazas                       427 non-null    float64
 9   potencia                     461 non-null    float64
 10  puertas                      464 non-null    int64
 11  color                        464 non-null    object
 12  precio                       464 non-null    int64
 13  vendedor_profesional         464 non-null    bool
 14  consumo_medio                174 non-null    float64
 15  certificado                  464 non-null    bool
 16  fecha_extraccion             464 non-null    datetime64[ns]
 17  referencia                   464 non-null    int64
 18  marca_sola                   464 non-null    object
 19  mes_matricula                464 non-null    int64
 20  anio_matricula               464 non-null    int64
 21  nombre_vendedor_profesional  464 non-null    string
 22  peninsula_y_baleares         464 non-null    bool
 23  comunidad                    461 non-null    object
dtypes: bool(4), datetime64[ns](1), float64(4), int64(5), object(9), string(1)
memory usage: 74.4+ KB

In [5]:
df_limpio["comunidad"].unique()

array(['Comunidad de Madrid', 'Andalucía', 'País Vasco', 'Cataluña',
       'Comunidad Valenciana', 'Aragón', 'Castilla y León', 'Navarra',
       'Castilla-La Mancha', 'Galicia', 'La Rioja', 'Región de Murcia',
       'Extremadura', nan], dtype=object)

In [6]:
df_limpio[df_limpio["comunidad"].isna()]

,modelo_titulo,provincia,kilometraje,combustible,distintivo_ambiental,garantia,cambio_automatico,carroceria,plazas,potencia,...,consumo_medio,certificado,fecha_extraccion,referencia,marca_sola,mes_matricula,anio_matricula,nombre_vendedor_profesional,peninsula_y_baleares,comunidad
371,Clase V EQV 300 Larga e100,NaN,8540,Eléctrico,0 EMISIONES,18.0,True,Pequeño,NaN,204.0,...,NaN,True,2025-02-18 12:05:16.733564,13800403,MERCEDES-BENZ,4,2022,MERCEDES CANARIAS LAS PALMAS,True,NaN
372,EQB 250,NaN,14720,Eléctrico,0 EMISIONES,36.0,True,Todo Terreno,5.0,190.0,...,NaN,True,2025-02-18 12:05:24.177183,14777875,MERCEDES-BENZ,7,2023,MERCEDES CANARIAS LAS PALMAS,True,NaN
381,Juke 1.6 Acenta 4x2 112,NaN,90336,Gasolina,C,12.0,False,Todo Terreno,5.0,112.0,...,6.9,False,2025-02-18 12:06:20.489508,15401172,NISSAN,2,2019,SHOPING CAR,True,NaN

In [12]:
longitudes = df_limpio["nombre_vendedor_profesional"].apply(lambda x: len(x) if pd.notna(x) else 0)


# Obtener la longitud máxima
longitud_maxima = longitudes.max()

longitud_maxima

np.int64(46)

In [4]:
# con esto sabréis la ruta actual

import os

ruta_actual = os.getcwd()

print(f"La ruta actual de trabajo es: {ruta_actual}")

La ruta actual de trabajo es: /home/bross/Codigo_HAB/PFB_coches/PFB_coches/temp