In [373]:
import pandas as pd
import numpy as np
import re

In [374]:
df = pd.read_csv("../data/coches_segunda_mano-19-02-2025.csv")

In [375]:
len(df)

7904

In [376]:
df =  df.drop_duplicates(subset=['referencia'], keep='first')

In [377]:
len(df)

4778

In [378]:
df

,marca,anio,localizacion,kilometraje,combustible,distintivo_ambiental,garantia,cambio,carroceria,plazas,...,puertas,color,precio,vendedor,consumo_medio,certificado,fecha_extraccion,referencia,url,ruta_imagen
0,PEUGEOT 308 1.4 95cv 5p.,05/2009,Lleida,142.137 km,Gasolina,C,12 meses,Manual,Berlina mediana o grande,NaN,...,5 Puertas,Gris,7.900 €\r\n13%\r\n6.900 €,ASTER AUTOS\r\nProfesional,NaN,No,2025-02-19 17:01:36.887580,ref14946771,https://www.autocasion.com/coches-segunda-mano...,../img/coches/14946771-0-5926368496749e1fa4cfb...
1,SEAT León ST 1.6 TDI CR 85 kW (115 CV) Start&S...,06/2020,Lleida,106.736 km,Diésel,NaN,12 meses,Manual,Familiar,NaN,...,5 Puertas,Blanco,13.500 €,ASTER AUTOS\r\nProfesional,NaN,No,2025-02-19 17:01:44.312012,ref14962083,https://www.autocasion.com/coches-segunda-mano...,../img/coches/14962083-0-824922025674e0c07cb9c...
2,PEUGEOT 308 1.5BlueHDi S&S Style 130,09/2019,Lleida,68.314 km,Diesel,C,12 meses,Manual,Berlina,5 asientos,...,5 Puertas,Gris,13.900 €,ASTER AUTOS\r\nProfesional,"Consumo medio\r\n3,60\r\nlitros/100 km",No,2025-02-19 17:01:54.282640,ref15014897,https://www.autocasion.com/coches-segunda-mano...,../img/coches/15014897-0-1402892972675898157d3...
3,OPEL Grandland X Grand Land 1.6CDTI Selective,10/2018,Lleida,55.531 km,Diésel,NaN,12 meses,Manual,"4x4, SUV o pickup",NaN,...,5 Puertas,Gris,17.950 €,ASTER AUTOS\r\nProfesional,NaN,No,2025-02-19 17:02:02.672957,ref15027844,https://www.autocasion.com/coches-segunda-mano...,../img/coches/15027844-0-557393874675b05f31fab...
4,AUDI A3 Sportback Sportback 35 TFSI 150cv,02/2021,Lleida,75.800 km,Gasolina,C,12 meses,Manual,Berlina mediana o grande,NaN,...,5 Puertas,Azul,24.900 €,ASTER AUTOS\r\nProfesional,NaN,No,2025-02-19 17:02:11.380113,ref15068938,https://www.autocasion.com/coches-segunda-mano...,../img/coches/15068938-0-21278795586762f4e3501...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7847,AUDI Q2 ADVANCED 30 TFSI 81(110) KW(CV) 6 VEL.,02/2021,Murcia,56.640 km,Gasolina,C,12 meses,Manual,"4x4, SUV o pickup",NaN,...,5 Puertas,GRIS MANHATTAN,24.000 €,AUDI HUERTAS MOTOR MURCIA\r\nProfesional,NaN,Si,2025-02-20 16:50:19.841595,ref15333890,https://www.autocasion.com/coches-segunda-mano...,../img/coches/91c126beae1477982e79150aa72153fc...
7848,VOLKSWAGEN Golf 2.0TDI Sport DSG7 110kW,11/2020,Madrid,42.000 km,Diesel,C,12 meses,Automático,Berlina,5 asientos,...,5 Puertas,Gris / Metalizado,25.990 €,Matexcar\r\nProfesional,"Consumo medio\r\n4,40\r\nlitros/100 km",No,2025-02-20 16:50:28.065854,ref15450596,https://www.autocasion.com/coches-segunda-mano...,../img/coches/1798790e897d8cfc4f01c5e9c342acfb...
7849,AUDI A6 Avant 40 TDI S tronic,04/2023,Murcia,24.304 km,Diesel,ECO,12 meses,Automático,Stationwagon,5 asientos,...,5 Puertas,AZUL FIRMAMENTO METALIZADO,53.900 €\r\n2%\r\n53.000 €,AUDI HUERTAS MOTOR MURCIA\r\nProfesional,"Consumo medio\r\n4,50\r\nlitros/100 km",No,2025-02-20 16:50:37.503167,ref15333884,https://www.autocasion.com/coches-segunda-mano...,../img/coches/ec0183657d36a2c20336c8656afc507c...
7902,VOLKSWAGEN Touran 2.0TDI Life DSG7 110kW,12/2024,Madrid,5.000 km,Diesel,C,12 meses,Automático,Monovolumen,7 asientos,...,5 Puertas,Blanco,43.750 €,F. Tomé\r\nProfesional,"Consumo medio\r\n0,00\r\nlitros/100 km",No,2025-02-20 16:58:50.765870,ref15414020,https://www.autocasion.com/coches-km0/km-0/vol...,../img/coches/15414020-0-232832890567acf283acf...
7903,VOLKSWAGEN Taigo 1.0 TSI Life 81kW,03/2024,Madrid,5.000 km,Gasolina,C,12 meses,Manual,Todo Terreno,5 asientos,...,5 Puertas,Negro,26.750 €,F. Tomé\r\nProfesional,"Consumo medio\r\n0,00\r\nlitros/100 km",No,2025-02-20 16:59:00.820588,ref12854839,https://www.autocasion.com/coches-km0/km-0/vol...,../img/coches/12854839-0-428134073166229674269...

In [379]:
df["consumo_medio"].value_counts()

consumo_medio
Consumo medio\r\n0,00\r\nlitros/100 km     1152
Consumo medio\r\n4,20\r\nlitros/100 km      109
Consumo medio\r\n4,60\r\nlitros/100 km      108
Consumo medio\r\n4,50\r\nlitros/100 km       98
Consumo medio\r\n4,30\r\nlitros/100 km       86
                                           ...
Consumo medio\r\n1,20\r\nlitros/100 km        1
Consumo medio\r\n10,90\r\nlitros/100 km       1
Consumo medio\r\n12,80\r\nlitros/100 km       1
Consumo medio\r\n2,60\r\nlitros/100 km        1
Consumo medio\r\n13,80\r\nlitros/100 km       1
Name: count, Length: 104, dtype: int64

In [380]:
df["consumo_medio"].isna().sum()

np.int64(1664)

In [381]:
# campo nuevo marca_sola

df['marca_sola'] = df['marca'].apply(lambda x: x.split()[0] if isinstance(x, str) else x)

In [382]:
df['marca_sola'].unique()

array(['PEUGEOT', 'SEAT', 'OPEL', 'AUDI', 'FIAT', 'RENAULT', 'HONDA',
       'SMART', 'TOYOTA', 'LEXUS', 'PORSCHE', 'JAGUAR', 'MERCEDES-BENZ',
       'MG', 'DS', 'VOLKSWAGEN', 'NISSAN', 'FORD', 'KIA', 'MINI', 'BMW',
       'VOLVO', 'HYUNDAI', 'CITROEN', 'MASERATI', 'JEEP', 'LAND-ROVER',
       'DACIA', 'DFSK', 'LYNK', 'KGM', 'TESLA', 'SUZUKI', 'SUBARU',
       'SKODA', 'MITSUBISHI', 'FERRARI', 'ALFA', 'MAZDA', 'GMC',
       'CHEVROLET', 'CADILLAC', 'DODGE', 'RAM', 'LANCIA', 'BENTLEY',
       'ABARTH', 'INFINITI', 'CUPRA', 'McLAREN', 'LAMBORGHINI', 'OMODA',
       'JAECOO', 'LINCOLN', 'CHRYSLER', 'ASTON', 'LEAPMOTOR', 'EVO',
       'SAAB', 'LOTUS', 'YES!'], dtype=object)

In [383]:
# renombrar "marca" por "modelo_titulo" y quitar marca

df.rename(columns={'marca': 'modelo_titulo'}, inplace=True)
df['modelo_titulo'] = df['modelo_titulo'].apply(lambda x: ' '.join(x.split()[1:]) if isinstance(x, str) else x)

In [384]:
df

,modelo_titulo,anio,localizacion,kilometraje,combustible,distintivo_ambiental,garantia,cambio,carroceria,plazas,...,color,precio,vendedor,consumo_medio,certificado,fecha_extraccion,referencia,url,ruta_imagen,marca_sola
0,308 1.4 95cv 5p.,05/2009,Lleida,142.137 km,Gasolina,C,12 meses,Manual,Berlina mediana o grande,NaN,...,Gris,7.900 €\r\n13%\r\n6.900 €,ASTER AUTOS\r\nProfesional,NaN,No,2025-02-19 17:01:36.887580,ref14946771,https://www.autocasion.com/coches-segunda-mano...,../img/coches/14946771-0-5926368496749e1fa4cfb...,PEUGEOT
1,León ST 1.6 TDI CR 85 kW (115 CV) Start&Stop S...,06/2020,Lleida,106.736 km,Diésel,NaN,12 meses,Manual,Familiar,NaN,...,Blanco,13.500 €,ASTER AUTOS\r\nProfesional,NaN,No,2025-02-19 17:01:44.312012,ref14962083,https://www.autocasion.com/coches-segunda-mano...,../img/coches/14962083-0-824922025674e0c07cb9c...,SEAT
2,308 1.5BlueHDi S&S Style 130,09/2019,Lleida,68.314 km,Diesel,C,12 meses,Manual,Berlina,5 asientos,...,Gris,13.900 €,ASTER AUTOS\r\nProfesional,"Consumo medio\r\n3,60\r\nlitros/100 km",No,2025-02-19 17:01:54.282640,ref15014897,https://www.autocasion.com/coches-segunda-mano...,../img/coches/15014897-0-1402892972675898157d3...,PEUGEOT
3,Grandland X Grand Land 1.6CDTI Selective,10/2018,Lleida,55.531 km,Diésel,NaN,12 meses,Manual,"4x4, SUV o pickup",NaN,...,Gris,17.950 €,ASTER AUTOS\r\nProfesional,NaN,No,2025-02-19 17:02:02.672957,ref15027844,https://www.autocasion.com/coches-segunda-mano...,../img/coches/15027844-0-557393874675b05f31fab...,OPEL
4,A3 Sportback Sportback 35 TFSI 150cv,02/2021,Lleida,75.800 km,Gasolina,C,12 meses,Manual,Berlina mediana o grande,NaN,...,Azul,24.900 €,ASTER AUTOS\r\nProfesional,NaN,No,2025-02-19 17:02:11.380113,ref15068938,https://www.autocasion.com/coches-segunda-mano...,../img/coches/15068938-0-21278795586762f4e3501...,AUDI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7847,Q2 ADVANCED 30 TFSI 81(110) KW(CV) 6 VEL.,02/2021,Murcia,56.640 km,Gasolina,C,12 meses,Manual,"4x4, SUV o pickup",NaN,...,GRIS MANHATTAN,24.000 €,AUDI HUERTAS MOTOR MURCIA\r\nProfesional,NaN,Si,2025-02-20 16:50:19.841595,ref15333890,https://www.autocasion.com/coches-segunda-mano...,../img/coches/91c126beae1477982e79150aa72153fc...,AUDI
7848,Golf 2.0TDI Sport DSG7 110kW,11/2020,Madrid,42.000 km,Diesel,C,12 meses,Automático,Berlina,5 asientos,...,Gris / Metalizado,25.990 €,Matexcar\r\nProfesional,"Consumo medio\r\n4,40\r\nlitros/100 km",No,2025-02-20 16:50:28.065854,ref15450596,https://www.autocasion.com/coches-segunda-mano...,../img/coches/1798790e897d8cfc4f01c5e9c342acfb...,VOLKSWAGEN
7849,A6 Avant 40 TDI S tronic,04/2023,Murcia,24.304 km,Diesel,ECO,12 meses,Automático,Stationwagon,5 asientos,...,AZUL FIRMAMENTO METALIZADO,53.900 €\r\n2%\r\n53.000 €,AUDI HUERTAS MOTOR MURCIA\r\nProfesional,"Consumo medio\r\n4,50\r\nlitros/100 km",No,2025-02-20 16:50:37.503167,ref15333884,https://www.autocasion.com/coches-segunda-mano...,../img/coches/ec0183657d36a2c20336c8656afc507c...,AUDI
7902,Touran 2.0TDI Life DSG7 110kW,12/2024,Madrid,5.000 km,Diesel,C,12 meses,Automático,Monovolumen,7 asientos,...,Blanco,43.750 €,F. Tomé\r\nProfesional,"Consumo medio\r\n0,00\r\nlitros/100 km",No,2025-02-20 16:58:50.765870,ref15414020,https://www.autocasion.com/coches-km0/km-0/vol...,../img/coches/15414020-0-232832890567acf283acf...,VOLKSWAGEN
7903,Taigo 1.0 TSI Life 81kW,03/2024,Madrid,5.000 km,Gasolina,C,12 meses,Manual,Todo Terreno,5 asientos,...,Negro,26.750 €,F. Tomé\r\nProfesional,"Consumo medio\r\n0,00\r\nlitros/100 km",No,2025-02-20 16:59:00.820588,ref12854839,https://www.autocasion.com/coches-km0/km-0/vol...,../img/coches/12854839-0-428134073166229674269...,VOLKSWAGEN

In [385]:
# sacar mes y año en columnas separadas

df[['mes_matricula', 'anio_matricula']] = df['anio'].str.split('/', expand=True)

df['mes_matricula'] = df['mes_matricula'].astype(int)
df['anio_matricula'] = df['anio_matricula'].astype(int)

df.drop(columns=["anio"], inplace=True)

In [386]:
def limpiar_kilometraje(valor):
    valor_limpio = valor.replace(".","").replace(" km","")
    return int(valor_limpio)

In [387]:
df["kilometraje"] = df["kilometraje"].apply(lambda x: limpiar_kilometraje(x) if isinstance(x, str) else np.nan)

In [388]:
df["garantia"].unique()

array(['12 meses', '24 meses', nan, 'Sí', 'No', '36 meses', '48 meses',
       '60 meses', '84 meses', '72 meses', '22 meses', '245 meses',
       '18 meses', '19 meses', '21 meses', '30 meses', '50 meses',
       '59 meses', '42 meses', '121 meses', '43 meses', '55 meses',
       '14 meses', '15 meses', '28 meses', '31 meses', '25 meses',
       '6 meses', '53 meses', '27 meses', '49 meses', '51 meses',
       '29 meses', '37 meses', '38 meses', '54 meses', '70 meses',
       '26 meses', '17 meses', '20 meses', '52 meses', '34 meses',
       '32 meses', '23 meses', '57 meses', '35 meses', '58 meses',
       '56 meses', '33 meses'], dtype=object)

In [389]:
df[df["garantia"] == " meses"]["vendedor"].unique()

array([], dtype=object)

In [390]:
df["garantia"] = df["garantia"].replace("No", 0)
df["garantia"] = df["garantia"].replace("Sí", np.nan)
df["garantia"] = pd.to_numeric(df["garantia"].str.replace(" meses", ""), errors='coerce')

In [391]:
df.head(10)

,modelo_titulo,localizacion,kilometraje,combustible,distintivo_ambiental,garantia,cambio,carroceria,plazas,potencia,...,vendedor,consumo_medio,certificado,fecha_extraccion,referencia,url,ruta_imagen,marca_sola,mes_matricula,anio_matricula
0,308 1.4 95cv 5p.,Lleida,142137,Gasolina,C,12.0,Manual,Berlina mediana o grande,NaN,95 cv,...,ASTER AUTOS\r\nProfesional,NaN,No,2025-02-19 17:01:36.887580,ref14946771,https://www.autocasion.com/coches-segunda-mano...,../img/coches/14946771-0-5926368496749e1fa4cfb...,PEUGEOT,5,2009
1,León ST 1.6 TDI CR 85 kW (115 CV) Start&Stop S...,Lleida,106736,Diésel,NaN,12.0,Manual,Familiar,NaN,116 cv,...,ASTER AUTOS\r\nProfesional,NaN,No,2025-02-19 17:01:44.312012,ref14962083,https://www.autocasion.com/coches-segunda-mano...,../img/coches/14962083-0-824922025674e0c07cb9c...,SEAT,6,2020
2,308 1.5BlueHDi S&S Style 130,Lleida,68314,Diesel,C,12.0,Manual,Berlina,5 asientos,130 cv,...,ASTER AUTOS\r\nProfesional,"Consumo medio\r\n3,60\r\nlitros/100 km",No,2025-02-19 17:01:54.282640,ref15014897,https://www.autocasion.com/coches-segunda-mano...,../img/coches/15014897-0-1402892972675898157d3...,PEUGEOT,9,2019
3,Grandland X Grand Land 1.6CDTI Selective,Lleida,55531,Diésel,NaN,12.0,Manual,"4x4, SUV o pickup",NaN,120 cv,...,ASTER AUTOS\r\nProfesional,NaN,No,2025-02-19 17:02:02.672957,ref15027844,https://www.autocasion.com/coches-segunda-mano...,../img/coches/15027844-0-557393874675b05f31fab...,OPEL,10,2018
4,A3 Sportback Sportback 35 TFSI 150cv,Lleida,75800,Gasolina,C,12.0,Manual,Berlina mediana o grande,NaN,150 cv,...,ASTER AUTOS\r\nProfesional,NaN,No,2025-02-19 17:02:11.380113,ref15068938,https://www.autocasion.com/coches-segunda-mano...,../img/coches/15068938-0-21278795586762f4e3501...,AUDI,2,2021
5,Corsa 1.2 (100CV) Elegance 5P,Lleida,93869,Gasolina,C,12.0,Manual,Berlina mediana o grande,NaN,100 cv,...,ASTER AUTOS\r\nProfesional,NaN,No,2025-02-19 17:02:19.805639,ref15068939,https://www.autocasion.com/coches-segunda-mano...,../img/coches/15068939-0-1743434596762f4e4aa06...,OPEL,4,2022
6,A1 Sportback 30 TFSI Black line,Lleida,68216,Gasolina,C,12.0,Manual,Berlina,5 asientos,116 cv,...,ASTER AUTOS\r\nProfesional,"Consumo medio\r\n4,90\r\nlitros/100 km",No,2025-02-19 17:02:31.877727,ref15141118,https://www.autocasion.com/coches-segunda-mano...,../img/coches/15141118-0-10526678326772f9e3c71...,AUDI,3,2019
7,500 1.2 Lounge,Lleida,93562,Gasolina,C,12.0,Manual,Berlina,4 asientos,69 cv,...,ASTER AUTOS\r\nProfesional,"Consumo medio\r\n5,10\r\nlitros/100 km",No,2025-02-19 17:02:40.488963,ref15195785,https://www.autocasion.com/coches-segunda-mano...,../img/coches/15195785-0-2330156200678023dd3c6...,FIAT,8,2017
8,308 1.6 THP Active,Lleida,135000,Gasolina,C,12.0,Manual,Berlina,5 asientos,125 cv,...,ASTER AUTOS\r\nProfesional,"Consumo medio\r\n5,60\r\nlitros/100 km",No,2025-02-19 17:02:49.506620,ref15239174,https://www.autocasion.com/coches-segunda-mano...,../img/coches/15239174-0-393456983767880dbc445...,PEUGEOT,3,2014
9,Astra 1.6CDTi S/S Dynamic 136,Lleida,109570,Diesel,C,12.0,Manual,Berlina,5 asientos,136 cv,...,ASTER AUTOS\r\nProfesional,"Consumo medio\r\n3,90\r\nlitros/100 km",No,2025-02-19 17:02:57.300519,ref15267813,https://www.autocasion.com/coches-segunda-mano...,../img/coches/15267813-0-526599784678e30ba8dff...,OPEL,2,2017

In [392]:
media_garantia = pd.to_numeric(round(df["garantia"].mean(), 0))
df['garantia'] = df["garantia"].fillna(media_garantia)

In [393]:
df["consumo_medio"].unique()

array([nan, 'Consumo medio\r\n3,60\r\nlitros/100 km',
       'Consumo medio\r\n4,90\r\nlitros/100 km',
       'Consumo medio\r\n5,10\r\nlitros/100 km',
       'Consumo medio\r\n5,60\r\nlitros/100 km',
       'Consumo medio\r\n3,90\r\nlitros/100 km',
       'Consumo medio\r\n4,40\r\nlitros/100 km',
       'Consumo medio\r\n7,40\r\nlitros/100 km',
       'Consumo medio\r\n9,10\r\nlitros/100 km',
       'Consumo medio\r\n5,20\r\nlitros/100 km',
       'Consumo medio\r\n3,20\r\nlitros/100 km',
       'Consumo medio\r\n8,40\r\nlitros/100 km',
       'Consumo medio\r\nlitros/100 km',
       'Consumo medio\r\n4,00\r\nlitros/100 km',
       'Consumo medio\r\n7,50\r\nlitros/100 km',
       'Consumo medio\r\n4,80\r\nlitros/100 km',
       'Consumo medio\r\n3,70\r\nlitros/100 km',
       'Consumo medio\r\n3,80\r\nlitros/100 km',
       'Consumo medio\r\n0,00\r\nlitros/100 km',
       'Consumo medio\r\n12,10\r\nlitros/100 km',
       'Consumo medio\r\n4,60\r\nlitros/100 km',
       'Consumo medio\r\n6,30\r\nlitros/100 km',
       'Consumo medio\r\n1,70\r\nlitros/100 km',
       'Consumo medio\r\n4,20\r\nlitros/100 km',
       'Consumo medio\r\n6,00\r\nlitros/100 km',
       'Consumo medio\r\n1,40\r\nlitros/100 km',
       'Consumo medio\r\n1,90\r\nlitros/100 km',
       'Consumo medio\r\n5,80\r\nlitros/100 km',
       'Consumo medio\r\n5,00\r\nlitros/100 km',
       'Consumo medio\r\n10,40\r\nlitros/100 km',
       'Consumo medio\r\n7,20\r\nlitros/100 km',
       'Consumo medio\r\n6,40\r\nlitros/100 km',
       'Consumo medio\r\n5,30\r\nlitros/100 km',
       'Consumo medio\r\n5,70\r\nlitros/100 km',
       'Consumo medio\r\n6,60\r\nlitros/100 km',
       'Consumo medio\r\n8,10\r\nlitros/100 km',
       'Consumo medio\r\n4,70\r\nlitros/100 km',
       'Consumo medio\r\n5,40\r\nlitros/100 km',
       'Consumo medio\r\n4,30\r\nlitros/100 km',
       'Consumo medio\r\n3,50\r\nlitros/100 km',
       'Consumo medio\r\n6,10\r\nlitros/100 km',
       'Consumo medio\r\n6,50\r\nlitros/100 km',
       'Consumo medio\r\n9,60\r\nlitros/100 km',
       'Consumo medio\r\n10,50\r\nlitros/100 km',
       'Consumo medio\r\n8,00\r\nlitros/100 km',
       'Consumo medio\r\n11,80\r\nlitros/100 km',
       'Consumo medio\r\n6,80\r\nlitros/100 km',
       'Consumo medio\r\n7,00\r\nlitros/100 km',
       'Consumo medio\r\n9,30\r\nlitros/100 km',
       'Consumo medio\r\n8,60\r\nlitros/100 km',
       'Consumo medio\r\n4,50\r\nlitros/100 km',
       'Consumo medio\r\n3,30\r\nlitros/100 km',
       'Consumo medio\r\n5,90\r\nlitros/100 km',
       'Consumo medio\r\n6,70\r\nlitros/100 km',
       'Consumo medio\r\n4,10\r\nlitros/100 km',
       'Consumo medio\r\n7,30\r\nlitros/100 km',
       'Consumo medio\r\n11,10\r\nlitros/100 km',
       'Consumo medio\r\n8,80\r\nlitros/100 km',
       'Consumo medio\r\n7,10\r\nlitros/100 km',
       'Consumo medio\r\n7,90\r\nlitros/100 km',
       'Consumo medio\r\n7,60\r\nlitros/100 km',
       'Consumo medio\r\n6,90\r\nlitros/100 km',
       'Consumo medio\r\n5,50\r\nlitros/100 km',
       'Consumo medio\r\n2,50\r\nlitros/100 km',
       'Consumo medio\r\n1,80\r\nlitros/100 km',
       'Consumo medio\r\n9,40\r\nlitros/100 km',
       'Consumo medio\r\n2,20\r\nlitros/100 km',
       'Consumo medio\r\n6,20\r\nlitros/100 km',
       'Consumo medio\r\n11,40\r\nlitros/100 km',
       'Consumo medio\r\n16,20\r\nlitros/100 km',
       'Consumo medio\r\n3,40\r\nlitros/100 km',
       'Consumo medio\r\n20,50\r\nlitros/100 km',
       'Consumo medio\r\n13,10\r\nlitros/100 km',
       'Consumo medio\r\n9,20\r\nlitros/100 km',
       'Consumo medio\r\n8,20\r\nlitros/100 km',
       'Consumo medio\r\n12,70\r\nlitros/100 km',
       'Consumo medio\r\n11,30\r\nlitros/100 km',
       'Consumo medio\r\n7,70\r\nlitros/100 km',
       'Consumo medio\r\n9,50\r\nlitros/100 km',
       'Consumo medio\r\n10,80\r\nlitros/100 km',
       'Consumo medio\r\n9,90\r\nlitros/100 km',
       'Consumo medio\r\n13,20\r\nlitros/100 km',
       'Consumo medio\r\n2,00\r\nlitros/100 km',
       'Consumo medio\r\n1,60\r\nlitros/100 km',
       'Consumo medio\r\n8,70\r\nlitros/100 km',
       'Consumo medio\r\n9,00\r\nlitros/100 km',
       'Consumo medio\r\n2,80\r\nlitros/100 km',
       'Consumo medio\r\n7,80\r\nlitros/100 km',
       'Consumo medio\r\n11,50\r\nlitros/100 km',
       'Consumo medio\r\n11,00\r\nlitros/100 km',
       'Consumo medio\r\n12,50\r\nlitros/100 km',
       'Consumo medio\r\n16,00\r\nlitros/100 km',
       'Consumo medio\r\n3,10\r\nlitros/100 km',
       'Consumo medio\r\n10,30\r\nlitros/100 km',
       'Consumo medio\r\n9,80\r\nlitros/100 km',
       'Consumo medio\r\n8,30\r\nlitros/100 km',
       'Consumo medio\r\n8,90\r\nlitros/100 km',
       'Consumo medio\r\n11,60\r\nlitros/100 km',
       'Consumo medio\r\n2,70\r\nlitros/100 km',
       'Consumo medio\r\n2,10\r\nlitros/100 km',
       'Consumo medio\r\n1,20\r\nlitros/100 km',
       'Consumo medio\r\n10,90\r\nlitros/100 km',
       'Consumo medio\r\n12,80\r\nlitros/100 km',
       'Consumo medio\r\n2,60\r\nlitros/100 km',
       'Consumo medio\r\n13,80\r\nlitros/100 km'], dtype=object)

In [394]:
# convertir a nan los que contengan \nlitros
# sustituir valor por solo lo que hay entre medio\n y \nlitros convertido a float redondeado a 2
# sustituir nans por media (22,5% en muestra: hay que ver porcentaje total de nans y hablar con grupo)


#df['consumo_medio'] = df['consumo_medio'].replace(r'.*\\nlitros.*', np.nan, regex=True)

# Paso 2: Sustituir el valor por solo lo que hay entre "medio\n" y "\nlitros" convertido a float redondeado a 2 decimales
#df['consumo_medio'] = df['consumo_medio'].apply(lambda x: float(re.search(r'medio\n(.*?)\nlitros', x).group(1)) if isinstance(x, str) and re.search(r'medio\n(.*?)\nlitros', x) else x)

# Paso 3: Sustituir NaNs por la media de la columna
#mean_value = df['consumo_medio'].mean()
# df['consumo_medio'] = df['consumo_medio'].fillna(mean_value)

In [395]:
df

,modelo_titulo,localizacion,kilometraje,combustible,distintivo_ambiental,garantia,cambio,carroceria,plazas,potencia,...,vendedor,consumo_medio,certificado,fecha_extraccion,referencia,url,ruta_imagen,marca_sola,mes_matricula,anio_matricula
0,308 1.4 95cv 5p.,Lleida,142137,Gasolina,C,12.0,Manual,Berlina mediana o grande,NaN,95 cv,...,ASTER AUTOS\r\nProfesional,NaN,No,2025-02-19 17:01:36.887580,ref14946771,https://www.autocasion.com/coches-segunda-mano...,../img/coches/14946771-0-5926368496749e1fa4cfb...,PEUGEOT,5,2009
1,León ST 1.6 TDI CR 85 kW (115 CV) Start&Stop S...,Lleida,106736,Diésel,NaN,12.0,Manual,Familiar,NaN,116 cv,...,ASTER AUTOS\r\nProfesional,NaN,No,2025-02-19 17:01:44.312012,ref14962083,https://www.autocasion.com/coches-segunda-mano...,../img/coches/14962083-0-824922025674e0c07cb9c...,SEAT,6,2020
2,308 1.5BlueHDi S&S Style 130,Lleida,68314,Diesel,C,12.0,Manual,Berlina,5 asientos,130 cv,...,ASTER AUTOS\r\nProfesional,"Consumo medio\r\n3,60\r\nlitros/100 km",No,2025-02-19 17:01:54.282640,ref15014897,https://www.autocasion.com/coches-segunda-mano...,../img/coches/15014897-0-1402892972675898157d3...,PEUGEOT,9,2019
3,Grandland X Grand Land 1.6CDTI Selective,Lleida,55531,Diésel,NaN,12.0,Manual,"4x4, SUV o pickup",NaN,120 cv,...,ASTER AUTOS\r\nProfesional,NaN,No,2025-02-19 17:02:02.672957,ref15027844,https://www.autocasion.com/coches-segunda-mano...,../img/coches/15027844-0-557393874675b05f31fab...,OPEL,10,2018
4,A3 Sportback Sportback 35 TFSI 150cv,Lleida,75800,Gasolina,C,12.0,Manual,Berlina mediana o grande,NaN,150 cv,...,ASTER AUTOS\r\nProfesional,NaN,No,2025-02-19 17:02:11.380113,ref15068938,https://www.autocasion.com/coches-segunda-mano...,../img/coches/15068938-0-21278795586762f4e3501...,AUDI,2,2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7847,Q2 ADVANCED 30 TFSI 81(110) KW(CV) 6 VEL.,Murcia,56640,Gasolina,C,12.0,Manual,"4x4, SUV o pickup",NaN,110 cv,...,AUDI HUERTAS MOTOR MURCIA\r\nProfesional,NaN,Si,2025-02-20 16:50:19.841595,ref15333890,https://www.autocasion.com/coches-segunda-mano...,../img/coches/91c126beae1477982e79150aa72153fc...,AUDI,2,2021
7848,Golf 2.0TDI Sport DSG7 110kW,Madrid,42000,Diesel,C,12.0,Automático,Berlina,5 asientos,150 cv,...,Matexcar\r\nProfesional,"Consumo medio\r\n4,40\r\nlitros/100 km",No,2025-02-20 16:50:28.065854,ref15450596,https://www.autocasion.com/coches-segunda-mano...,../img/coches/1798790e897d8cfc4f01c5e9c342acfb...,VOLKSWAGEN,11,2020
7849,A6 Avant 40 TDI S tronic,Murcia,24304,Diesel,ECO,12.0,Automático,Stationwagon,5 asientos,204 cv,...,AUDI HUERTAS MOTOR MURCIA\r\nProfesional,"Consumo medio\r\n4,50\r\nlitros/100 km",No,2025-02-20 16:50:37.503167,ref15333884,https://www.autocasion.com/coches-segunda-mano...,../img/coches/ec0183657d36a2c20336c8656afc507c...,AUDI,4,2023
7902,Touran 2.0TDI Life DSG7 110kW,Madrid,5000,Diesel,C,12.0,Automático,Monovolumen,7 asientos,150 cv,...,F. Tomé\r\nProfesional,"Consumo medio\r\n0,00\r\nlitros/100 km",No,2025-02-20 16:58:50.765870,ref15414020,https://www.autocasion.com/coches-km0/km-0/vol...,../img/coches/15414020-0-232832890567acf283acf...,VOLKSWAGEN,12,2024
7903,Taigo 1.0 TSI Life 81kW,Madrid,5000,Gasolina,C,12.0,Manual,Todo Terreno,5 asientos,110 cv,...,F. Tomé\r\nProfesional,"Consumo medio\r\n0,00\r\nlitros/100 km",No,2025-02-20 16:59:00.820588,ref12854839,https://www.autocasion.com/coches-km0/km-0/vol...,../img/coches/12854839-0-428134073166229674269...,VOLKSWAGEN,3,2024

In [396]:
df['referencia'] = pd.to_numeric(df['referencia'].str.replace('ref', ''), errors='coerce')

In [397]:
df['vendedor']=df['vendedor'].fillna("-")
df["nombre_vendedor_profesional"] = pd.Series(dtype="string")
mask = df['vendedor'].str.endswith('\nProfesional')
df.loc[mask, 'nombre_vendedor_profesional'] = df.loc[mask, 'vendedor'].str.split('\nProfesional').str[0]
df['vendedor'] = df['vendedor'].apply(lambda x: True if '\nProfesional' in x else False)
df.rename(columns={'vendedor':'vendedor_profesional'}, inplace=True)
df['vendedor_profesional'].astype(bool)

0       True
1       True
2       True
3       True
4       True
        ...
7847    True
7848    True
7849    True
7902    True
7903    True
Name: vendedor_profesional, Length: 4778, dtype: bool

In [398]:
df['color']=df['color'].apply(lambda x: x.upper())

In [399]:
# Traducir al español los colores en inglés y alemán
# "plateado" va al saco de grises

df.loc[df["color"].str.contains("BLACK|SCHWARZ", regex=True), "color"] = "NEGRO"
df.loc[df["color"].str.contains("WHITE|WEISS", regex=True), "color"] = "BLANCO"
df.loc[df["color"].str.contains("RED|ROT", regex=True), "color"] = "ROJO"
df.loc[df["color"].str.contains("BLUE|BLAU", regex=True), "color"] = "AZUL"
df.loc[df["color"].str.contains("GRAY|GREY|GRAU|PLATEADO|SILVER", regex=True), "color"] = "GRIS"

In [400]:
df['color'] = df['color'].str.split().str[0]

In [401]:
colores = ["NEGRO", "BLANCO", "AZUL", "ROJO", "GRIS"]
df['color'] = df['color'].apply(lambda x: x if x in colores else 'OTROS')

In [402]:
df.drop(columns=["vendedor_profesional", "mes_matricula", "anio_matricula"])

,modelo_titulo,localizacion,kilometraje,combustible,distintivo_ambiental,garantia,cambio,carroceria,plazas,potencia,...,color,precio,consumo_medio,certificado,fecha_extraccion,referencia,url,ruta_imagen,marca_sola,nombre_vendedor_profesional
0,308 1.4 95cv 5p.,Lleida,142137,Gasolina,C,12.0,Manual,Berlina mediana o grande,NaN,95 cv,...,GRIS,7.900 €\r\n13%\r\n6.900 €,NaN,No,2025-02-19 17:01:36.887580,14946771,https://www.autocasion.com/coches-segunda-mano...,../img/coches/14946771-0-5926368496749e1fa4cfb...,PEUGEOT,ASTER AUTOS
1,León ST 1.6 TDI CR 85 kW (115 CV) Start&Stop S...,Lleida,106736,Diésel,NaN,12.0,Manual,Familiar,NaN,116 cv,...,BLANCO,13.500 €,NaN,No,2025-02-19 17:01:44.312012,14962083,https://www.autocasion.com/coches-segunda-mano...,../img/coches/14962083-0-824922025674e0c07cb9c...,SEAT,ASTER AUTOS
2,308 1.5BlueHDi S&S Style 130,Lleida,68314,Diesel,C,12.0,Manual,Berlina,5 asientos,130 cv,...,GRIS,13.900 €,"Consumo medio\r\n3,60\r\nlitros/100 km",No,2025-02-19 17:01:54.282640,15014897,https://www.autocasion.com/coches-segunda-mano...,../img/coches/15014897-0-1402892972675898157d3...,PEUGEOT,ASTER AUTOS
3,Grandland X Grand Land 1.6CDTI Selective,Lleida,55531,Diésel,NaN,12.0,Manual,"4x4, SUV o pickup",NaN,120 cv,...,GRIS,17.950 €,NaN,No,2025-02-19 17:02:02.672957,15027844,https://www.autocasion.com/coches-segunda-mano...,../img/coches/15027844-0-557393874675b05f31fab...,OPEL,ASTER AUTOS
4,A3 Sportback Sportback 35 TFSI 150cv,Lleida,75800,Gasolina,C,12.0,Manual,Berlina mediana o grande,NaN,150 cv,...,AZUL,24.900 €,NaN,No,2025-02-19 17:02:11.380113,15068938,https://www.autocasion.com/coches-segunda-mano...,../img/coches/15068938-0-21278795586762f4e3501...,AUDI,ASTER AUTOS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7847,Q2 ADVANCED 30 TFSI 81(110) KW(CV) 6 VEL.,Murcia,56640,Gasolina,C,12.0,Manual,"4x4, SUV o pickup",NaN,110 cv,...,GRIS,24.000 €,NaN,Si,2025-02-20 16:50:19.841595,15333890,https://www.autocasion.com/coches-segunda-mano...,../img/coches/91c126beae1477982e79150aa72153fc...,AUDI,AUDI HUERTAS MOTOR MURCIA
7848,Golf 2.0TDI Sport DSG7 110kW,Madrid,42000,Diesel,C,12.0,Automático,Berlina,5 asientos,150 cv,...,GRIS,25.990 €,"Consumo medio\r\n4,40\r\nlitros/100 km",No,2025-02-20 16:50:28.065854,15450596,https://www.autocasion.com/coches-segunda-mano...,../img/coches/1798790e897d8cfc4f01c5e9c342acfb...,VOLKSWAGEN,Matexcar
7849,A6 Avant 40 TDI S tronic,Murcia,24304,Diesel,ECO,12.0,Automático,Stationwagon,5 asientos,204 cv,...,AZUL,53.900 €\r\n2%\r\n53.000 €,"Consumo medio\r\n4,50\r\nlitros/100 km",No,2025-02-20 16:50:37.503167,15333884,https://www.autocasion.com/coches-segunda-mano...,../img/coches/ec0183657d36a2c20336c8656afc507c...,AUDI,AUDI HUERTAS MOTOR MURCIA
7902,Touran 2.0TDI Life DSG7 110kW,Madrid,5000,Diesel,C,12.0,Automático,Monovolumen,7 asientos,150 cv,...,BLANCO,43.750 €,"Consumo medio\r\n0,00\r\nlitros/100 km",No,2025-02-20 16:58:50.765870,15414020,https://www.autocasion.com/coches-km0/km-0/vol...,../img/coches/15414020-0-232832890567acf283acf...,VOLKSWAGEN,F. Tomé
7903,Taigo 1.0 TSI Life 81kW,Madrid,5000,Gasolina,C,12.0,Manual,Todo Terreno,5 asientos,110 cv,...,NEGRO,26.750 €,"Consumo medio\r\n0,00\r\nlitros/100 km",No,2025-02-20 16:59:00.820588,12854839,https://www.autocasion.com/coches-km0/km-0/vol...,../img/coches/12854839-0-428134073166229674269...,VOLKSWAGEN,F. Tomé

In [403]:
df['color'].value_counts()

color
BLANCO    1437
GRIS      1178
NEGRO      676
AZUL       572
OTROS      546
ROJO       369
Name: count, dtype: int64

In [404]:
df["carroceria"].unique()

array(['Berlina mediana o grande', 'Familiar', 'Berlina',
       '4x4, SUV o pickup', 'Todo Terreno', 'Convertible', 'Coupe',
       'Deportivo o coupé', 'Stationwagon', 'Monovolumen', 'Pequeño',
       'Descapotable o convertible', 'Roadster', 'Targa', '-', nan],
      dtype=object)

In [405]:
df['carroceria'].value_counts()

carroceria
Todo Terreno                  1400
Berlina                       1206
4x4, SUV o pickup              758
Berlina mediana o grande       611
Monovolumen                    210
Stationwagon                   156
Familiar                       126
Coupe                          122
Pequeño                         70
Deportivo o coupé               38
Convertible                     33
Descapotable o convertible      22
Roadster                        16
-                                5
Targa                            1
Name: count, dtype: int64

In [406]:
df["carroceria"] = df["carroceria"].replace("Berlina mediana o grande", "Berlina")
df["carroceria"] = df["carroceria"].replace("Targa", "Berlina")
df["carroceria"] = df["carroceria"].replace("Coupe", "Deportivo o coupé ")
df["carroceria"] = df["carroceria"].replace("Convertible", "Descapotable o convertible")
df["carroceria"] = df["carroceria"].replace("Roadster", "Descapotable o convertible")
df["carroceria"] = df["carroceria"].replace("-", "Pequeño")
df["carroceria"] = df["carroceria"].replace("Stationwagon", "Familiar")

In [407]:
df['carroceria'].value_counts()

carroceria
Berlina                       1818
Todo Terreno                  1400
4x4, SUV o pickup              758
Familiar                       282
Monovolumen                    210
Deportivo o coupé              122
Pequeño                         75
Descapotable o convertible      71
Deportivo o coupé               38
Name: count, dtype: int64

In [408]:
df["plazas"] = pd.to_numeric(df["plazas"].str.replace(" asientos", ""), errors='coerce')

In [409]:
df.head(3)

,modelo_titulo,localizacion,kilometraje,combustible,distintivo_ambiental,garantia,cambio,carroceria,plazas,potencia,...,consumo_medio,certificado,fecha_extraccion,referencia,url,ruta_imagen,marca_sola,mes_matricula,anio_matricula,nombre_vendedor_profesional
0,308 1.4 95cv 5p.,Lleida,142137,Gasolina,C,12.0,Manual,Berlina,NaN,95 cv,...,NaN,No,2025-02-19 17:01:36.887580,14946771,https://www.autocasion.com/coches-segunda-mano...,../img/coches/14946771-0-5926368496749e1fa4cfb...,PEUGEOT,5,2009,ASTER AUTOS
1,León ST 1.6 TDI CR 85 kW (115 CV) Start&Stop S...,Lleida,106736,Diésel,NaN,12.0,Manual,Familiar,NaN,116 cv,...,NaN,No,2025-02-19 17:01:44.312012,14962083,https://www.autocasion.com/coches-segunda-mano...,../img/coches/14962083-0-824922025674e0c07cb9c...,SEAT,6,2020,ASTER AUTOS
2,308 1.5BlueHDi S&S Style 130,Lleida,68314,Diesel,C,12.0,Manual,Berlina,5.0,130 cv,...,"Consumo medio\r\n3,60\r\nlitros/100 km",No,2025-02-19 17:01:54.282640,15014897,https://www.autocasion.com/coches-segunda-mano...,../img/coches/15014897-0-1402892972675898157d3...,PEUGEOT,9,2019,ASTER AUTOS

In [439]:
df['puertas'].value_counts()

puertas
5    4267
4     274
2     123
3     113
0       1
Name: count, dtype: int64

In [ ]:
df["puertas"] = pd.to_numeric(df["puertas"].str.replace(" Puertas", ""), errors='coerce')

In [440]:
df['puertas'] = df['puertas'].apply(lambda x: np.nan if x == 0 else x)

In [441]:
df['puertas'].value_counts()

puertas
5.0    4267
4.0     274
2.0     123
3.0     113
Name: count, dtype: int64

In [411]:
df.drop(columns=["vendedor_profesional", "mes_matricula", "anio_matricula"])

,modelo_titulo,localizacion,kilometraje,combustible,distintivo_ambiental,garantia,cambio,carroceria,plazas,potencia,...,color,precio,consumo_medio,certificado,fecha_extraccion,referencia,url,ruta_imagen,marca_sola,nombre_vendedor_profesional
0,308 1.4 95cv 5p.,Lleida,142137,Gasolina,C,12.0,Manual,Berlina,NaN,95 cv,...,GRIS,7.900 €\r\n13%\r\n6.900 €,NaN,No,2025-02-19 17:01:36.887580,14946771,https://www.autocasion.com/coches-segunda-mano...,../img/coches/14946771-0-5926368496749e1fa4cfb...,PEUGEOT,ASTER AUTOS
1,León ST 1.6 TDI CR 85 kW (115 CV) Start&Stop S...,Lleida,106736,Diésel,NaN,12.0,Manual,Familiar,NaN,116 cv,...,BLANCO,13.500 €,NaN,No,2025-02-19 17:01:44.312012,14962083,https://www.autocasion.com/coches-segunda-mano...,../img/coches/14962083-0-824922025674e0c07cb9c...,SEAT,ASTER AUTOS
2,308 1.5BlueHDi S&S Style 130,Lleida,68314,Diesel,C,12.0,Manual,Berlina,5.0,130 cv,...,GRIS,13.900 €,"Consumo medio\r\n3,60\r\nlitros/100 km",No,2025-02-19 17:01:54.282640,15014897,https://www.autocasion.com/coches-segunda-mano...,../img/coches/15014897-0-1402892972675898157d3...,PEUGEOT,ASTER AUTOS
3,Grandland X Grand Land 1.6CDTI Selective,Lleida,55531,Diésel,NaN,12.0,Manual,"4x4, SUV o pickup",NaN,120 cv,...,GRIS,17.950 €,NaN,No,2025-02-19 17:02:02.672957,15027844,https://www.autocasion.com/coches-segunda-mano...,../img/coches/15027844-0-557393874675b05f31fab...,OPEL,ASTER AUTOS
4,A3 Sportback Sportback 35 TFSI 150cv,Lleida,75800,Gasolina,C,12.0,Manual,Berlina,NaN,150 cv,...,AZUL,24.900 €,NaN,No,2025-02-19 17:02:11.380113,15068938,https://www.autocasion.com/coches-segunda-mano...,../img/coches/15068938-0-21278795586762f4e3501...,AUDI,ASTER AUTOS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7847,Q2 ADVANCED 30 TFSI 81(110) KW(CV) 6 VEL.,Murcia,56640,Gasolina,C,12.0,Manual,"4x4, SUV o pickup",NaN,110 cv,...,GRIS,24.000 €,NaN,Si,2025-02-20 16:50:19.841595,15333890,https://www.autocasion.com/coches-segunda-mano...,../img/coches/91c126beae1477982e79150aa72153fc...,AUDI,AUDI HUERTAS MOTOR MURCIA
7848,Golf 2.0TDI Sport DSG7 110kW,Madrid,42000,Diesel,C,12.0,Automático,Berlina,5.0,150 cv,...,GRIS,25.990 €,"Consumo medio\r\n4,40\r\nlitros/100 km",No,2025-02-20 16:50:28.065854,15450596,https://www.autocasion.com/coches-segunda-mano...,../img/coches/1798790e897d8cfc4f01c5e9c342acfb...,VOLKSWAGEN,Matexcar
7849,A6 Avant 40 TDI S tronic,Murcia,24304,Diesel,ECO,12.0,Automático,Familiar,5.0,204 cv,...,AZUL,53.900 €\r\n2%\r\n53.000 €,"Consumo medio\r\n4,50\r\nlitros/100 km",No,2025-02-20 16:50:37.503167,15333884,https://www.autocasion.com/coches-segunda-mano...,../img/coches/ec0183657d36a2c20336c8656afc507c...,AUDI,AUDI HUERTAS MOTOR MURCIA
7902,Touran 2.0TDI Life DSG7 110kW,Madrid,5000,Diesel,C,12.0,Automático,Monovolumen,7.0,150 cv,...,BLANCO,43.750 €,"Consumo medio\r\n0,00\r\nlitros/100 km",No,2025-02-20 16:58:50.765870,15414020,https://www.autocasion.com/coches-km0/km-0/vol...,../img/coches/15414020-0-232832890567acf283acf...,VOLKSWAGEN,F. Tomé
7903,Taigo 1.0 TSI Life 81kW,Madrid,5000,Gasolina,C,12.0,Manual,Todo Terreno,5.0,110 cv,...,NEGRO,26.750 €,"Consumo medio\r\n0,00\r\nlitros/100 km",No,2025-02-20 16:59:00.820588,12854839,https://www.autocasion.com/coches-km0/km-0/vol...,../img/coches/12854839-0-428134073166229674269...,VOLKSWAGEN,F. Tomé

In [412]:
print(len(df['consumo_medio']))
print(df['consumo_medio'].isnull().sum())

4778
1664

In [413]:
# Paso 1: Sustituir por NaN los valores que contengan "medio\n0,00\nlitros" o "medio\nlitros"
#df['consumo_medio'] = df['consumo_medio'].replace(
#    [r'.*medio\n0,00\nlitros.*', r'.*medio\nlitros.*'], np.nan, regex=True)

# Paso 2: Dejar solo el número entre "medio\n" y "\nlitros" y convertir a float redondeado a 2 decimales
#df['consumo_medio'] = df['consumo_medio'].str.extract(r'medio\n(.*?)\nlitros')[0]
#df['consumo_medio'] = df['consumo_medio'].str.replace(',', '.').astype(float).round(2)

# mean_value = df['consumo_medio'].mean().round(2)
# df['consumo_medio'].fillna(mean_value, inplace=True)

In [ ]:
#NUEVO
# Paso 1: Sustituir por NaN los valores que contengan "medio\n0,00\nlitros" o "medio\nlitros"
df['consumo_medio'] = df['consumo_medio'].replace([r'.*Consumo medio\r\n0,00\r\nlitros.*', r'.*Consumo medio\r\nlitros.*'], np.nan, regex=True)

# Paso 2: Dejar solo el número entre "medio\n" y "\nlitros" y convertir a float redondeado a 2 decimales
df['consumo_medio'] = df['consumo_medio'].str.extract(r'Consumo medio\r\n([\d,]+)\r\nlitros')[0]
df['consumo_medio'] = df['consumo_medio'].str.replace(',', '.').astype(float).round(2)
# mean_value = df['consumo_medio'].mean().round(2)
# df['consumo_medio'].fillna(mean_value, inplace=True)

In [415]:
print(len(df['consumo_medio']))
print(df['consumo_medio'].isnull().sum())

4778
2891

In [416]:
df.drop(columns=["vendedor_profesional", "mes_matricula", "anio_matricula"])

,modelo_titulo,localizacion,kilometraje,combustible,distintivo_ambiental,garantia,cambio,carroceria,plazas,potencia,...,color,precio,consumo_medio,certificado,fecha_extraccion,referencia,url,ruta_imagen,marca_sola,nombre_vendedor_profesional
0,308 1.4 95cv 5p.,Lleida,142137,Gasolina,C,12.0,Manual,Berlina,NaN,95 cv,...,GRIS,7.900 €\r\n13%\r\n6.900 €,NaN,No,2025-02-19 17:01:36.887580,14946771,https://www.autocasion.com/coches-segunda-mano...,../img/coches/14946771-0-5926368496749e1fa4cfb...,PEUGEOT,ASTER AUTOS
1,León ST 1.6 TDI CR 85 kW (115 CV) Start&Stop S...,Lleida,106736,Diésel,NaN,12.0,Manual,Familiar,NaN,116 cv,...,BLANCO,13.500 €,NaN,No,2025-02-19 17:01:44.312012,14962083,https://www.autocasion.com/coches-segunda-mano...,../img/coches/14962083-0-824922025674e0c07cb9c...,SEAT,ASTER AUTOS
2,308 1.5BlueHDi S&S Style 130,Lleida,68314,Diesel,C,12.0,Manual,Berlina,5.0,130 cv,...,GRIS,13.900 €,3.6,No,2025-02-19 17:01:54.282640,15014897,https://www.autocasion.com/coches-segunda-mano...,../img/coches/15014897-0-1402892972675898157d3...,PEUGEOT,ASTER AUTOS
3,Grandland X Grand Land 1.6CDTI Selective,Lleida,55531,Diésel,NaN,12.0,Manual,"4x4, SUV o pickup",NaN,120 cv,...,GRIS,17.950 €,NaN,No,2025-02-19 17:02:02.672957,15027844,https://www.autocasion.com/coches-segunda-mano...,../img/coches/15027844-0-557393874675b05f31fab...,OPEL,ASTER AUTOS
4,A3 Sportback Sportback 35 TFSI 150cv,Lleida,75800,Gasolina,C,12.0,Manual,Berlina,NaN,150 cv,...,AZUL,24.900 €,NaN,No,2025-02-19 17:02:11.380113,15068938,https://www.autocasion.com/coches-segunda-mano...,../img/coches/15068938-0-21278795586762f4e3501...,AUDI,ASTER AUTOS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7847,Q2 ADVANCED 30 TFSI 81(110) KW(CV) 6 VEL.,Murcia,56640,Gasolina,C,12.0,Manual,"4x4, SUV o pickup",NaN,110 cv,...,GRIS,24.000 €,NaN,Si,2025-02-20 16:50:19.841595,15333890,https://www.autocasion.com/coches-segunda-mano...,../img/coches/91c126beae1477982e79150aa72153fc...,AUDI,AUDI HUERTAS MOTOR MURCIA
7848,Golf 2.0TDI Sport DSG7 110kW,Madrid,42000,Diesel,C,12.0,Automático,Berlina,5.0,150 cv,...,GRIS,25.990 €,4.4,No,2025-02-20 16:50:28.065854,15450596,https://www.autocasion.com/coches-segunda-mano...,../img/coches/1798790e897d8cfc4f01c5e9c342acfb...,VOLKSWAGEN,Matexcar
7849,A6 Avant 40 TDI S tronic,Murcia,24304,Diesel,ECO,12.0,Automático,Familiar,5.0,204 cv,...,AZUL,53.900 €\r\n2%\r\n53.000 €,4.5,No,2025-02-20 16:50:37.503167,15333884,https://www.autocasion.com/coches-segunda-mano...,../img/coches/ec0183657d36a2c20336c8656afc507c...,AUDI,AUDI HUERTAS MOTOR MURCIA
7902,Touran 2.0TDI Life DSG7 110kW,Madrid,5000,Diesel,C,12.0,Automático,Monovolumen,7.0,150 cv,...,BLANCO,43.750 €,NaN,No,2025-02-20 16:58:50.765870,15414020,https://www.autocasion.com/coches-km0/km-0/vol...,../img/coches/15414020-0-232832890567acf283acf...,VOLKSWAGEN,F. Tomé
7903,Taigo 1.0 TSI Life 81kW,Madrid,5000,Gasolina,C,12.0,Manual,Todo Terreno,5.0,110 cv,...,NEGRO,26.750 €,NaN,No,2025-02-20 16:59:00.820588,12854839,https://www.autocasion.com/coches-km0/km-0/vol...,../img/coches/12854839-0-428134073166229674269...,VOLKSWAGEN,F. Tomé

In [417]:
df["consumo_medio"].value_counts()

consumo_medio
4.2     109
4.6     108
4.5      98
5.1      86
4.3      86
       ...
1.2       1
10.9      1
12.8      1
2.6       1
13.8      1
Name: count, Length: 102, dtype: int64

In [418]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4778 entries, 0 to 7903
Data columns (total 24 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   modelo_titulo                4778 non-null   object
 1   localizacion                 4778 non-null   object
 2   kilometraje                  4778 non-null   int64
 3   combustible                  4751 non-null   object
 4   distintivo_ambiental         4377 non-null   object
 5   garantia                     4778 non-null   float64
 6   cambio                       4776 non-null   object
 7   carroceria                   4774 non-null   object
 8   plazas                       3241 non-null   float64
 9   potencia                     4778 non-null   object
 10  puertas                      4778 non-null   int64
 11  color                        4778 non-null   object
 12  precio                       4777 non-null   object
 13  vendedor_profesional         4778 non-null   bool
 14  consumo_medio                1887 non-null   float64
 15  certificado                  4778 non-null   object
 16  fecha_extraccion             4778 non-null   object
 17  referencia                   4778 non-null   int64
 18  url                          4778 non-null   object
 19  ruta_imagen                  4769 non-null   object
 20  marca_sola                   4778 non-null   object
 21  mes_matricula                4778 non-null   int64
 22  anio_matricula               4778 non-null   int64
 23  nombre_vendedor_profesional  4776 non-null   string
dtypes: bool(1), float64(3), int64(5), object(14), string(1)
memory usage: 900.5+ KB

In [419]:
df["precio"].unique()

array(['7.900 €\r\n13%\r\n6.900 €', '13.500 €', '13.900 €', ...,
       '86.900 €\r\n2%\r\n85.500 €', '53.900 €\r\n2%\r\n53.000 €',
       '43.750 €'], shape=(1713,), dtype=object)

In [420]:
df['precio'] = df['precio'].str.replace('.', '').str.replace(' €', '')
df['precio'] = df['precio'].str.split('\n').str[0]
df['precio'] = pd.to_numeric(df['precio'], errors='coerce')

In [421]:
df["cambio"].unique()

array(['Manual', 'Automático', nan], dtype=object)

In [422]:
df.drop(columns=["vendedor_profesional", "mes_matricula", "anio_matricula"])

,modelo_titulo,localizacion,kilometraje,combustible,distintivo_ambiental,garantia,cambio,carroceria,plazas,potencia,...,color,precio,consumo_medio,certificado,fecha_extraccion,referencia,url,ruta_imagen,marca_sola,nombre_vendedor_profesional
0,308 1.4 95cv 5p.,Lleida,142137,Gasolina,C,12.0,Manual,Berlina,NaN,95 cv,...,GRIS,7900.0,NaN,No,2025-02-19 17:01:36.887580,14946771,https://www.autocasion.com/coches-segunda-mano...,../img/coches/14946771-0-5926368496749e1fa4cfb...,PEUGEOT,ASTER AUTOS
1,León ST 1.6 TDI CR 85 kW (115 CV) Start&Stop S...,Lleida,106736,Diésel,NaN,12.0,Manual,Familiar,NaN,116 cv,...,BLANCO,13500.0,NaN,No,2025-02-19 17:01:44.312012,14962083,https://www.autocasion.com/coches-segunda-mano...,../img/coches/14962083-0-824922025674e0c07cb9c...,SEAT,ASTER AUTOS
2,308 1.5BlueHDi S&S Style 130,Lleida,68314,Diesel,C,12.0,Manual,Berlina,5.0,130 cv,...,GRIS,13900.0,3.6,No,2025-02-19 17:01:54.282640,15014897,https://www.autocasion.com/coches-segunda-mano...,../img/coches/15014897-0-1402892972675898157d3...,PEUGEOT,ASTER AUTOS
3,Grandland X Grand Land 1.6CDTI Selective,Lleida,55531,Diésel,NaN,12.0,Manual,"4x4, SUV o pickup",NaN,120 cv,...,GRIS,17950.0,NaN,No,2025-02-19 17:02:02.672957,15027844,https://www.autocasion.com/coches-segunda-mano...,../img/coches/15027844-0-557393874675b05f31fab...,OPEL,ASTER AUTOS
4,A3 Sportback Sportback 35 TFSI 150cv,Lleida,75800,Gasolina,C,12.0,Manual,Berlina,NaN,150 cv,...,AZUL,24900.0,NaN,No,2025-02-19 17:02:11.380113,15068938,https://www.autocasion.com/coches-segunda-mano...,../img/coches/15068938-0-21278795586762f4e3501...,AUDI,ASTER AUTOS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7847,Q2 ADVANCED 30 TFSI 81(110) KW(CV) 6 VEL.,Murcia,56640,Gasolina,C,12.0,Manual,"4x4, SUV o pickup",NaN,110 cv,...,GRIS,24000.0,NaN,Si,2025-02-20 16:50:19.841595,15333890,https://www.autocasion.com/coches-segunda-mano...,../img/coches/91c126beae1477982e79150aa72153fc...,AUDI,AUDI HUERTAS MOTOR MURCIA
7848,Golf 2.0TDI Sport DSG7 110kW,Madrid,42000,Diesel,C,12.0,Automático,Berlina,5.0,150 cv,...,GRIS,25990.0,4.4,No,2025-02-20 16:50:28.065854,15450596,https://www.autocasion.com/coches-segunda-mano...,../img/coches/1798790e897d8cfc4f01c5e9c342acfb...,VOLKSWAGEN,Matexcar
7849,A6 Avant 40 TDI S tronic,Murcia,24304,Diesel,ECO,12.0,Automático,Familiar,5.0,204 cv,...,AZUL,53900.0,4.5,No,2025-02-20 16:50:37.503167,15333884,https://www.autocasion.com/coches-segunda-mano...,../img/coches/ec0183657d36a2c20336c8656afc507c...,AUDI,AUDI HUERTAS MOTOR MURCIA
7902,Touran 2.0TDI Life DSG7 110kW,Madrid,5000,Diesel,C,12.0,Automático,Monovolumen,7.0,150 cv,...,BLANCO,43750.0,NaN,No,2025-02-20 16:58:50.765870,15414020,https://www.autocasion.com/coches-km0/km-0/vol...,../img/coches/15414020-0-232832890567acf283acf...,VOLKSWAGEN,F. Tomé
7903,Taigo 1.0 TSI Life 81kW,Madrid,5000,Gasolina,C,12.0,Manual,Todo Terreno,5.0,110 cv,...,NEGRO,26750.0,NaN,No,2025-02-20 16:59:00.820588,12854839,https://www.autocasion.com/coches-km0/km-0/vol...,../img/coches/12854839-0-428134073166229674269...,VOLKSWAGEN,F. Tomé

In [423]:
df["potencia"].unique()

array(['95 cv', '116 cv', '130 cv', '120 cv', '150 cv', '100 cv', '69 cv',
       '125 cv', '136 cv', '140 cv', '115 cv', '201 cv', '90 cv',
       '122 cv', '184 cv', '462 cv', '340 cv', '306 cv', '170 cv',
       '258 cv', '75 cv', '110 cv', '109 cv', '245 cv', '200 cv',
       '204 cv', '388 cv', '163 cv', '220 cv', '320 cv', '114 cv',
       '218 cv', '83 cv', '286 cv', '265 cv', '224 cv', '390 cv',
       '380 cv', '195 cv', '157 cv', '308 cv', '84 cv', '449 cv',
       '285 cv', '326 cv', '230 cv', '231 cv', '190 cv', '240 cv',
       '149 cv', '225 cv', '261 cv', '99 cv', '145 cv', '- cv', '160 cv',
       '112 cv', '165 cv', '305 cv', '177 cv', '180 cv', '299 cv',
       '460 cv', '510 cv', '185 cv', '68 cv', '263 cv', '197 cv',
       '155 cv', '71 cv', '253 cv', '407 cv', '205 cv', '570 cv',
       '235 cv', '350 cv', '129 cv', '85 cv', '179 cv', '132 cv',
       '523 cv', '333 cv', '313 cv', '111 cv', '223 cv', '300 cv',
       '80 cv', '102 cv', '187 cv', '105 cv', '310 cv', '426 cv',
       '360 cv', '420 cv', '470 cv', '760 cv', '668 cv', '237 cv',
       '540 cv', '106 cv', '156 cv', '135 cv', '70 cv', '82 cv',
       '1.290 cv', '272 cv', '421 cv', '141 cv', '260 cv', '528 cv',
       '193 cv', '131 cv', '91 cv', '81 cv', '63 cv', '374 cv', '334 cv',
       '119 cv', '490 cv', '250 cv', '143 cv', '222 cv', '441 cv',
       '525 cv', '211 cv', '174 cv', '262 cv', '178 cv', '124 cv',
       '283 cv', '181 cv', '188 cv', '327 cv', '121 cv', '158 cv',
       '182 cv', '210 cv', '292 cv', '98 cv', '370 cv', '194 cv',
       '101 cv', '409 cv', '92 cv', '312 cv', '244 cv', '217 cv',
       '367 cv', '514 cv', '550 cv', '610 cv', '147 cv', '440 cv',
       '67 cv', '243 cv', '214 cv', '183 cv', '252 cv', '138 cv', '66 cv',
       '72 cv', '97 cv', '423 cv', '319 cv', '228 cv', '585 cv', '162 cv',
       '575 cv', '635 cv', '202 cv', '455 cv', '213 cv', '825 cv',
       '354 cv', '352 cv', '650 cv', '435 cv', '400 cv', '249 cv',
       '480 cv', '600 cv', '280 cv', '520 cv', '571 cv', '118 cv',
       '215 cv', '339 cv', '530 cv', '298 cv', '739 cv', '560 cv',
       '398 cv', '88 cv', '73 cv', '476 cv', '79 cv', '166 cv', '314 cv',
       '60 cv', '241 cv', '196 cv', '269 cv', '229 cv', '381 cv',
       '117 cv', '403 cv', '408 cv', '522 cv', '233 cv', '330 cv',
       '295 cv', '750 cv', '666 cv', '288 cv', '192 cv', '238 cv',
       '500 cv', '325 cv', '630 cv', '700 cv', '199 cv', '680 cv',
       '513 cv', '422 cv', '450 cv', '347 cv', '186 cv', '161 cv',
       '459 cv', '159 cv', '720 cv', '290 cv', '176 cv', '203 cv',
       '321 cv', '234 cv', '128 cv', '468 cv', '65 cv', '248 cv',
       '146 cv', '349 cv', '551 cv', '351 cv', '94 cv', '405 cv',
       '103 cv', '394 cv', '544 cv', '107 cv', '108 cv', '123 cv',
       '126 cv', '598 cv', '727 cv', '603 cv', '404 cv', '385 cv',
       '428 cv', '270 cv', '256 cv', '104 cv', '275 cv'], dtype=object)

In [424]:
df['potencia'] = df['potencia'].str.replace(' cv', '')
df['potencia'] = pd.to_numeric(df['potencia'], errors='coerce')

In [425]:
df.drop(columns=["vendedor_profesional", "mes_matricula", "anio_matricula"])

,modelo_titulo,localizacion,kilometraje,combustible,distintivo_ambiental,garantia,cambio,carroceria,plazas,potencia,...,color,precio,consumo_medio,certificado,fecha_extraccion,referencia,url,ruta_imagen,marca_sola,nombre_vendedor_profesional
0,308 1.4 95cv 5p.,Lleida,142137,Gasolina,C,12.0,Manual,Berlina,NaN,95.0,...,GRIS,7900.0,NaN,No,2025-02-19 17:01:36.887580,14946771,https://www.autocasion.com/coches-segunda-mano...,../img/coches/14946771-0-5926368496749e1fa4cfb...,PEUGEOT,ASTER AUTOS
1,León ST 1.6 TDI CR 85 kW (115 CV) Start&Stop S...,Lleida,106736,Diésel,NaN,12.0,Manual,Familiar,NaN,116.0,...,BLANCO,13500.0,NaN,No,2025-02-19 17:01:44.312012,14962083,https://www.autocasion.com/coches-segunda-mano...,../img/coches/14962083-0-824922025674e0c07cb9c...,SEAT,ASTER AUTOS
2,308 1.5BlueHDi S&S Style 130,Lleida,68314,Diesel,C,12.0,Manual,Berlina,5.0,130.0,...,GRIS,13900.0,3.6,No,2025-02-19 17:01:54.282640,15014897,https://www.autocasion.com/coches-segunda-mano...,../img/coches/15014897-0-1402892972675898157d3...,PEUGEOT,ASTER AUTOS
3,Grandland X Grand Land 1.6CDTI Selective,Lleida,55531,Diésel,NaN,12.0,Manual,"4x4, SUV o pickup",NaN,120.0,...,GRIS,17950.0,NaN,No,2025-02-19 17:02:02.672957,15027844,https://www.autocasion.com/coches-segunda-mano...,../img/coches/15027844-0-557393874675b05f31fab...,OPEL,ASTER AUTOS
4,A3 Sportback Sportback 35 TFSI 150cv,Lleida,75800,Gasolina,C,12.0,Manual,Berlina,NaN,150.0,...,AZUL,24900.0,NaN,No,2025-02-19 17:02:11.380113,15068938,https://www.autocasion.com/coches-segunda-mano...,../img/coches/15068938-0-21278795586762f4e3501...,AUDI,ASTER AUTOS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7847,Q2 ADVANCED 30 TFSI 81(110) KW(CV) 6 VEL.,Murcia,56640,Gasolina,C,12.0,Manual,"4x4, SUV o pickup",NaN,110.0,...,GRIS,24000.0,NaN,Si,2025-02-20 16:50:19.841595,15333890,https://www.autocasion.com/coches-segunda-mano...,../img/coches/91c126beae1477982e79150aa72153fc...,AUDI,AUDI HUERTAS MOTOR MURCIA
7848,Golf 2.0TDI Sport DSG7 110kW,Madrid,42000,Diesel,C,12.0,Automático,Berlina,5.0,150.0,...,GRIS,25990.0,4.4,No,2025-02-20 16:50:28.065854,15450596,https://www.autocasion.com/coches-segunda-mano...,../img/coches/1798790e897d8cfc4f01c5e9c342acfb...,VOLKSWAGEN,Matexcar
7849,A6 Avant 40 TDI S tronic,Murcia,24304,Diesel,ECO,12.0,Automático,Familiar,5.0,204.0,...,AZUL,53900.0,4.5,No,2025-02-20 16:50:37.503167,15333884,https://www.autocasion.com/coches-segunda-mano...,../img/coches/ec0183657d36a2c20336c8656afc507c...,AUDI,AUDI HUERTAS MOTOR MURCIA
7902,Touran 2.0TDI Life DSG7 110kW,Madrid,5000,Diesel,C,12.0,Automático,Monovolumen,7.0,150.0,...,BLANCO,43750.0,NaN,No,2025-02-20 16:58:50.765870,15414020,https://www.autocasion.com/coches-km0/km-0/vol...,../img/coches/15414020-0-232832890567acf283acf...,VOLKSWAGEN,F. Tomé
7903,Taigo 1.0 TSI Life 81kW,Madrid,5000,Gasolina,C,12.0,Manual,Todo Terreno,5.0,110.0,...,NEGRO,26750.0,NaN,No,2025-02-20 16:59:00.820588,12854839,https://www.autocasion.com/coches-km0/km-0/vol...,../img/coches/12854839-0-428134073166229674269...,VOLKSWAGEN,F. Tomé

In [426]:
fuera_de_peninsula_baleares = ["Tenerife", "Las Palmas", "Ceuta", "Melilla"]
df['peninsula_y_baleares'] = True
df.loc[df['localizacion'].isin(fuera_de_peninsula_baleares), 'peninsula_y_baleares'] = False

In [427]:
df.drop(columns=["vendedor_profesional", "mes_matricula", "anio_matricula"])

,modelo_titulo,localizacion,kilometraje,combustible,distintivo_ambiental,garantia,cambio,carroceria,plazas,potencia,...,precio,consumo_medio,certificado,fecha_extraccion,referencia,url,ruta_imagen,marca_sola,nombre_vendedor_profesional,peninsula_y_baleares
0,308 1.4 95cv 5p.,Lleida,142137,Gasolina,C,12.0,Manual,Berlina,NaN,95.0,...,7900.0,NaN,No,2025-02-19 17:01:36.887580,14946771,https://www.autocasion.com/coches-segunda-mano...,../img/coches/14946771-0-5926368496749e1fa4cfb...,PEUGEOT,ASTER AUTOS,True
1,León ST 1.6 TDI CR 85 kW (115 CV) Start&Stop S...,Lleida,106736,Diésel,NaN,12.0,Manual,Familiar,NaN,116.0,...,13500.0,NaN,No,2025-02-19 17:01:44.312012,14962083,https://www.autocasion.com/coches-segunda-mano...,../img/coches/14962083-0-824922025674e0c07cb9c...,SEAT,ASTER AUTOS,True
2,308 1.5BlueHDi S&S Style 130,Lleida,68314,Diesel,C,12.0,Manual,Berlina,5.0,130.0,...,13900.0,3.6,No,2025-02-19 17:01:54.282640,15014897,https://www.autocasion.com/coches-segunda-mano...,../img/coches/15014897-0-1402892972675898157d3...,PEUGEOT,ASTER AUTOS,True
3,Grandland X Grand Land 1.6CDTI Selective,Lleida,55531,Diésel,NaN,12.0,Manual,"4x4, SUV o pickup",NaN,120.0,...,17950.0,NaN,No,2025-02-19 17:02:02.672957,15027844,https://www.autocasion.com/coches-segunda-mano...,../img/coches/15027844-0-557393874675b05f31fab...,OPEL,ASTER AUTOS,True
4,A3 Sportback Sportback 35 TFSI 150cv,Lleida,75800,Gasolina,C,12.0,Manual,Berlina,NaN,150.0,...,24900.0,NaN,No,2025-02-19 17:02:11.380113,15068938,https://www.autocasion.com/coches-segunda-mano...,../img/coches/15068938-0-21278795586762f4e3501...,AUDI,ASTER AUTOS,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7847,Q2 ADVANCED 30 TFSI 81(110) KW(CV) 6 VEL.,Murcia,56640,Gasolina,C,12.0,Manual,"4x4, SUV o pickup",NaN,110.0,...,24000.0,NaN,Si,2025-02-20 16:50:19.841595,15333890,https://www.autocasion.com/coches-segunda-mano...,../img/coches/91c126beae1477982e79150aa72153fc...,AUDI,AUDI HUERTAS MOTOR MURCIA,True
7848,Golf 2.0TDI Sport DSG7 110kW,Madrid,42000,Diesel,C,12.0,Automático,Berlina,5.0,150.0,...,25990.0,4.4,No,2025-02-20 16:50:28.065854,15450596,https://www.autocasion.com/coches-segunda-mano...,../img/coches/1798790e897d8cfc4f01c5e9c342acfb...,VOLKSWAGEN,Matexcar,True
7849,A6 Avant 40 TDI S tronic,Murcia,24304,Diesel,ECO,12.0,Automático,Familiar,5.0,204.0,...,53900.0,4.5,No,2025-02-20 16:50:37.503167,15333884,https://www.autocasion.com/coches-segunda-mano...,../img/coches/ec0183657d36a2c20336c8656afc507c...,AUDI,AUDI HUERTAS MOTOR MURCIA,True
7902,Touran 2.0TDI Life DSG7 110kW,Madrid,5000,Diesel,C,12.0,Automático,Monovolumen,7.0,150.0,...,43750.0,NaN,No,2025-02-20 16:58:50.765870,15414020,https://www.autocasion.com/coches-km0/km-0/vol...,../img/coches/15414020-0-232832890567acf283acf...,VOLKSWAGEN,F. Tomé,True
7903,Taigo 1.0 TSI Life 81kW,Madrid,5000,Gasolina,C,12.0,Manual,Todo Terreno,5.0,110.0,...,26750.0,NaN,No,2025-02-20 16:59:00.820588,12854839,https://www.autocasion.com/coches-km0/km-0/vol...,../img/coches/12854839-0-428134073166229674269...,VOLKSWAGEN,F. Tomé,True

In [428]:
df["certificado"].unique()

array(['No', 'Si'], dtype=object)

In [429]:
df["certificado"] = df["certificado"].replace("No", False)
df["certificado"] = df["certificado"].replace("Sí", True)
df["certificado"] = df["certificado"].astype(bool)

In [430]:
df['fecha_extraccion'] = pd.to_datetime(df['fecha_extraccion'])

In [431]:
df.drop(columns=["vendedor_profesional", "mes_matricula", "anio_matricula"])

,modelo_titulo,localizacion,kilometraje,combustible,distintivo_ambiental,garantia,cambio,carroceria,plazas,potencia,...,precio,consumo_medio,certificado,fecha_extraccion,referencia,url,ruta_imagen,marca_sola,nombre_vendedor_profesional,peninsula_y_baleares
0,308 1.4 95cv 5p.,Lleida,142137,Gasolina,C,12.0,Manual,Berlina,NaN,95.0,...,7900.0,NaN,False,2025-02-19 17:01:36.887580,14946771,https://www.autocasion.com/coches-segunda-mano...,../img/coches/14946771-0-5926368496749e1fa4cfb...,PEUGEOT,ASTER AUTOS,True
1,León ST 1.6 TDI CR 85 kW (115 CV) Start&Stop S...,Lleida,106736,Diésel,NaN,12.0,Manual,Familiar,NaN,116.0,...,13500.0,NaN,False,2025-02-19 17:01:44.312012,14962083,https://www.autocasion.com/coches-segunda-mano...,../img/coches/14962083-0-824922025674e0c07cb9c...,SEAT,ASTER AUTOS,True
2,308 1.5BlueHDi S&S Style 130,Lleida,68314,Diesel,C,12.0,Manual,Berlina,5.0,130.0,...,13900.0,3.6,False,2025-02-19 17:01:54.282640,15014897,https://www.autocasion.com/coches-segunda-mano...,../img/coches/15014897-0-1402892972675898157d3...,PEUGEOT,ASTER AUTOS,True
3,Grandland X Grand Land 1.6CDTI Selective,Lleida,55531,Diésel,NaN,12.0,Manual,"4x4, SUV o pickup",NaN,120.0,...,17950.0,NaN,False,2025-02-19 17:02:02.672957,15027844,https://www.autocasion.com/coches-segunda-mano...,../img/coches/15027844-0-557393874675b05f31fab...,OPEL,ASTER AUTOS,True
4,A3 Sportback Sportback 35 TFSI 150cv,Lleida,75800,Gasolina,C,12.0,Manual,Berlina,NaN,150.0,...,24900.0,NaN,False,2025-02-19 17:02:11.380113,15068938,https://www.autocasion.com/coches-segunda-mano...,../img/coches/15068938-0-21278795586762f4e3501...,AUDI,ASTER AUTOS,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7847,Q2 ADVANCED 30 TFSI 81(110) KW(CV) 6 VEL.,Murcia,56640,Gasolina,C,12.0,Manual,"4x4, SUV o pickup",NaN,110.0,...,24000.0,NaN,True,2025-02-20 16:50:19.841595,15333890,https://www.autocasion.com/coches-segunda-mano...,../img/coches/91c126beae1477982e79150aa72153fc...,AUDI,AUDI HUERTAS MOTOR MURCIA,True
7848,Golf 2.0TDI Sport DSG7 110kW,Madrid,42000,Diesel,C,12.0,Automático,Berlina,5.0,150.0,...,25990.0,4.4,False,2025-02-20 16:50:28.065854,15450596,https://www.autocasion.com/coches-segunda-mano...,../img/coches/1798790e897d8cfc4f01c5e9c342acfb...,VOLKSWAGEN,Matexcar,True
7849,A6 Avant 40 TDI S tronic,Murcia,24304,Diesel,ECO,12.0,Automático,Familiar,5.0,204.0,...,53900.0,4.5,False,2025-02-20 16:50:37.503167,15333884,https://www.autocasion.com/coches-segunda-mano...,../img/coches/ec0183657d36a2c20336c8656afc507c...,AUDI,AUDI HUERTAS MOTOR MURCIA,True
7902,Touran 2.0TDI Life DSG7 110kW,Madrid,5000,Diesel,C,12.0,Automático,Monovolumen,7.0,150.0,...,43750.0,NaN,False,2025-02-20 16:58:50.765870,15414020,https://www.autocasion.com/coches-km0/km-0/vol...,../img/coches/15414020-0-232832890567acf283acf...,VOLKSWAGEN,F. Tomé,True
7903,Taigo 1.0 TSI Life 81kW,Madrid,5000,Gasolina,C,12.0,Manual,Todo Terreno,5.0,110.0,...,26750.0,NaN,False,2025-02-20 16:59:00.820588,12854839,https://www.autocasion.com/coches-km0/km-0/vol...,../img/coches/12854839-0-428134073166229674269...,VOLKSWAGEN,F. Tomé,True

In [432]:
df.rename(columns={'cambio': 'cambio_automatico'}, inplace=True)
df['cambio_automatico'] = df['cambio_automatico'].apply(lambda x: True if x == 'Automático' else False)

In [433]:
df['combustible'].unique()

array(['Gasolina', 'Diésel', 'Diesel', 'Híbrido', 'Híbrido Enchufable',
       'Corriente eléctrica', 'Gasolina y corriente eléctrica',
       'Diesel y corriente eléctrica', 'Eléctrico', nan, 'Gasolina/gas',
       'Gas'], dtype=object)

In [434]:
 # combustible
df["combustible"] = df["combustible"].replace("Diesel", "Diésel")
df["combustible"] = df["combustible"].replace("Gasolina y corriente eléctrica", "Híbrido")
df["combustible"] = df["combustible"].replace("Corriente eléctrica", "Eléctrico")
df["combustible"] = df["combustible"].replace("Gas", "Gasolina")
df["combustible"] = df["combustible"].replace("Gasolina/gas", "Gasolina")
df["combustible"] = df["combustible"].replace("Diesel y corriente eléctrica", "Híbrido")

In [435]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4778 entries, 0 to 7903
Data columns (total 25 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   modelo_titulo                4778 non-null   object
 1   localizacion                 4778 non-null   object
 2   kilometraje                  4778 non-null   int64
 3   combustible                  4751 non-null   object
 4   distintivo_ambiental         4377 non-null   object
 5   garantia                     4778 non-null   float64
 6   cambio_automatico            4778 non-null   bool
 7   carroceria                   4774 non-null   object
 8   plazas                       3241 non-null   float64
 9   potencia                     4753 non-null   float64
 10  puertas                      4778 non-null   int64
 11  color                        4778 non-null   object
 12  precio                       4777 non-null   float64
 13  vendedor_profesional         4778 non-null   bool
 14  consumo_medio                1887 non-null   float64
 15  certificado                  4778 non-null   bool
 16  fecha_extraccion             4778 non-null   datetime64[ns]
 17  referencia                   4778 non-null   int64
 18  url                          4778 non-null   object
 19  ruta_imagen                  4769 non-null   object
 20  marca_sola                   4778 non-null   object
 21  mes_matricula                4778 non-null   int64
 22  anio_matricula               4778 non-null   int64
 23  nombre_vendedor_profesional  4776 non-null   string
 24  peninsula_y_baleares         4778 non-null   bool
dtypes: bool(4), datetime64[ns](1), float64(5), int64(5), object(9), string(1)
memory usage: 839.9+ KB

In [436]:
df[df['nombre_vendedor_profesional'].isnull()]

,modelo_titulo,localizacion,kilometraje,combustible,distintivo_ambiental,garantia,cambio_automatico,carroceria,plazas,potencia,...,certificado,fecha_extraccion,referencia,url,ruta_imagen,marca_sola,mes_matricula,anio_matricula,nombre_vendedor_profesional,peninsula_y_baleares
20,Clase CLS Deportivo 306cv Automático de 4 Puertas,Valencia,160998,Gasolina,C,17.0,True,Deportivo o coupé,4.0,306.0,...,False,2025-02-19 17:05:00.782488,12450562,https://www.autocasion.com/coches-segunda-mano...,../img/coches/ec1924d9bb44f7828cbf5e02ab21f089...,MERCEDES-BENZ,2,2012,<NA>,True
398,Clase GLE 350d 4Matic Aut.,Jaén,142000,Diésel,C,12.0,True,Todo Terreno,5.0,272.0,...,False,2025-02-19 18:09:03.198231,14346634,https://www.autocasion.com/coches-segunda-mano...,NaN,MERCEDES-BENZ,2,2020,<NA>,True

In [438]:
df[df['kilometraje'] > 300000].sort_values('kilometraje', ascending=False)

,modelo_titulo,localizacion,kilometraje,combustible,distintivo_ambiental,garantia,cambio_automatico,carroceria,plazas,potencia,...,certificado,fecha_extraccion,referencia,url,ruta_imagen,marca_sola,mes_matricula,anio_matricula,nombre_vendedor_profesional,peninsula_y_baleares
1086,600 MHEV 1.2 74kW (100CV) DDCT La prima,Sevilla,999999,Gasolina,C,24.0,True,"4x4, SUV o pickup",NaN,100.0,...,True,2025-02-19 20:04:30.569045,15452536,https://www.autocasion.com/coches-segunda-mano...,../img/coches/15452536-0-229346912067b5f43400c...,FIAT,6,2024,STELLANTIS & YOU SEVILLA - SAN LAZARO,True
4387,Prius Prius+ 1.8 Eco,Málaga,743182,Híbrido,ECO,12.0,True,Monovolumen,7.0,136.0,...,False,2025-02-20 06:15:58.107607,15455823,https://www.autocasion.com/coches-segunda-mano...,../img/coches/092d617a7580e3a2996ab1d188efc664...,TOYOTA,2,2019,IMPO EXPO by 5210,True
1019,C4 ë -C4 Feel Pack 100kW,Madrid,558497,Eléctrico,0 EMISIONES,12.0,True,Pequeño,NaN,NaN,...,False,2025-02-19 19:54:11.144246,15454592,https://www.autocasion.com/coches-segunda-mano...,../img/coches/15454592-0-31134034467b618e23cc8...,CITROEN,5,2021,CAR10 Mostoles,True
4368,C4 ë -C4 Feel Pack 100kW,Toledo,558497,Eléctrico,0 EMISIONES,12.0,True,Pequeño,NaN,NaN,...,False,2025-02-20 06:12:45.057353,15454601,https://www.autocasion.com/coches-segunda-mano...,../img/coches/15454601-0-31134034467b619308e04...,CITROEN,5,2021,CAR10 Toledo,True
2024,Clase CLS 320CDI Aut.,Murcia,353187,Diésel,B,15.0,True,Deportivo o coupé,4.0,224.0,...,False,2025-02-19 22:54:28.213323,14541889,https://www.autocasion.com/coches-segunda-mano...,../img/coches/8ad81ef24637ccf6f06bdfe439d21a14...,MERCEDES-BENZ,12,2007,Merino Autocasion,True
317,Clase C 220CDI Avantgarde Aut.,Murcia,350000,Diésel,B,12.0,True,Berlina,5.0,170.0,...,False,2025-02-19 17:55:32.180308,14186724,https://www.autocasion.com/coches-segunda-mano...,../img/coches/cddb0186766f0ca8fe0d6fada8b1520e...,MERCEDES-BENZ,9,2008,Media Automoción,True
615,A3 2.0TDI Ambition S-Tronic,Madrid,330000,Diésel,B,12.0,True,Berlina,5.0,140.0,...,False,2025-02-19 18:46:10.515644,14264937,https://www.autocasion.com/coches-segunda-mano...,../img/coches/6546acdace2a4c410410f0e3fd46df33...,AUDI,3,2006,Autocaravanasycoches.com,True
2327,Fabia 1.4 TDI 69CV 5p.,Málaga,325000,Diésel,NaN,12.0,False,Pequeño,NaN,69.0,...,False,2025-02-19 23:47:52.720381,15440732,https://www.autocasion.com/coches-segunda-mano...,../img/coches/15440732-0-12536058467b39a151a48...,SKODA,4,2007,M.DOMENECH,True
3487,Clase E 220 CDI,Asturias,320000,Diésel,NaN,12.0,False,Berlina,5.0,150.0,...,False,2025-02-20 03:47:05.734240,14987475,https://www.autocasion.com/coches-segunda-mano...,../img/coches/39ef5a3f6c62739a149be098211348ed...,MERCEDES-BENZ,1,2002,Vican Motor,True
7383,307 1.6HDI X-Line 110,Madrid,313069,Diésel,B,12.0,False,Berlina,5.0,110.0,...,False,2025-02-20 15:12:26.003630,15119068,https://www.autocasion.com/coches-segunda-mano...,../img/coches/15119068-0-2329426015676d07b9d8a...,PEUGEOT,2,2006,RUTA 66,True
613,Clase V 220 CDI Trend,Madrid,312000,Diésel,NaN,12.0,False,Monovolumen,7.0,122.0,...,False,2025-02-19 18:45:52.745923,14264574,https://www.autocasion.com/coches-segunda-mano...,../img/coches/5be645368e9ca57ce75738aa211d64ee...,MERCEDES-BENZ,3,2002,Autocaravanasycoches.com,True
2860,Auris 1.4D-4D,Valencia,312000,Diésel,B,17.0,False,Berlina,5.0,90.0,...,False,2025-02-20 02:00:53.720013,15455744,https://www.autocasion.com/coches-segunda-mano...,../img/coches/15455744-0-70128746067b65827f413...,TOYOTA,3,2009,CSV MOTOR VALENCIA,True
135,/ SSANGYONG Rodius 270 Xdi Limited,Toledo,310000,Diésel,B,12.0,False,Monovolumen,7.0,165.0,...,False,2025-02-19 17:24:16.712246,15442026,https://www.autocasion.com/coches-segunda-mano...,../img/coches/6fe0b35be34745475835d8273c865582...,KGM,4,2008,MAXTER AUTOS,True
7188,C8 2.0HDI Seduction 135,Lleida,308000,Diésel,B,12.0,False,Monovolumen,5.0,136.0,...,False,2025-02-20 14:39:00.749930,15007135,https://www.autocasion.com/coches-segunda-mano...,../img/coches/38245ed9a04a5786fb68b556d54ee7d0...,CITROEN,6,2011,COMERCIAL VICTOR,True
7475,Freelander 2.0 XEDI,Granada,300320,Diésel,NaN,12.0,False,Todo Terreno,5.0,97.0,...,False,2025-02-20 15:28:03.296894,15456964,https://www.autocasion.com/coches-segunda-mano...,../img/coches/15456964-0-351024717667b70358649...,LAND-ROVER,9,2000,AUTOBAEZ HERMANOS,True