In [430]:
import pandas as pd
import numpy as np
import re

In [431]:
df = pd.read_csv("coches_segunda_mano-17-02-2025.csv")

In [432]:
df

,marca,anio,localizacion,kilometraje,combustible,distintivo_ambiental,garantia,cambio,carroceria,plazas,potencia,puertas,color,precio,vendedor,consumo_medio,certificado,fecha_extraccion,referencia
0,PEUGEOT 308 SW 1.5 BlueHDi S&S Allure 130,01/2021,Sevilla,156.000 km,Diesel,C,12 meses,Manual,Stationwagon,5 asientos,130 cv,5 Puertas,Blanco / Metalizado,11.990 €,MOTOR CLUB SEVILLA\nProfesional,"Consumo medio\n0,00\nlitros/100 km",No,2025-02-17 19:26:27.595606,ref15276957
1,VOLVO XC60 B4 R-Design AWD Aut.,01/2021,Sevilla,95.000 km,Diesel,ECO,12 meses,Automático,Todo Terreno,5 asientos,197 cv,5 Puertas,Azul / Metalizado,39.990 €,MOTOR CLUB SEVILLA\nProfesional,"Consumo medio\n5,50\nlitros/100 km",No,2025-02-17 19:26:35.003246,ref15168174
2,PEUGEOT Rifter 1.5BlueHDi S&S Long Active Pack...,09/2020,Almería,115.000 km,Diesel,C,12 meses,Manual,Monovolumen,5 asientos,131 cv,5 Puertas,Negro,18.500 €,AUTOMERCURY\nProfesional,"Consumo medio\n4,30\nlitros/100 km",No,2025-02-17 19:26:44.036638,ref13903932
3,KIA Sportage Todoterreno 136cv Automático de 4...,10/2023,Valencia,21.470 km,NaN,NaN,12 meses,Automático,"4x4, SUV o pickup",NaN,136 cv,4 Puertas,PLATA,31.460 €,LEASING AUTOMOBILE\nProfesional,NaN,No,2025-02-17 19:26:52.390413,ref15317252
4,AUDI Q8 s-line,08/2023,Valencia,17.290 km,Diésel,NaN,12 meses,Automático,"4x4, SUV o pickup",NaN,286 cv,4 Puertas,BLANCO,72.274 €,LEASING AUTOMOBILE\nProfesional,NaN,No,2025-02-17 19:27:07.527248,ref15218308
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,SEAT Tarraco 1.5 TSI S&S Style 150,09/2019,Almería,71.800 km,Gasolina,C,24 meses,Manual,Todo Terreno,5 asientos,150 cv,5 Puertas,Gris,23.900 €,INDALO MOTOR Concesionario Oficial SEAT\nProfe...,"Consumo medio\n5,80\nlitros/100 km",No,2025-02-17 19:37:41.617133,ref15066087
76,RENAULT Captur TCe Techno 67kW,03/2024,Madrid,18.426 km,Gasolina,C,12 meses,Manual,Todo Terreno,5 asientos,90 cv,5 Puertas,Gris / Metalizado,21.290 €\n6%\n19.990 €,CLICARS MADRID\nProfesional,"Consumo medio\n0,00\nlitros/100 km",No,2025-02-17 19:37:49.595653,ref15390517
77,CUPRA Formentor 1.5 TSI 150 DSG,06/2024,Almería,3.000 km,Gasolina,C,36 meses,Automático,Todo Terreno,5 asientos,150 cv,5 Puertas,Blanco,29.000 €,INDALO MOTOR Concesionario Oficial SEAT\nProfe...,"Consumo medio\n5,50\nlitros/100 km",No,2025-02-17 19:37:59.121730,ref15063293
78,FORD Puma 1.0 EcoBoost ST-Line X 125,02/2020,Albacete,35.700 km,Gasolina,C,12 meses,Manual,Todo Terreno,5 asientos,125 cv,5 Puertas,Rojo,19.900 €,AUTOMOVILES GARRIDO\nProfesional,"Consumo medio\n4,50\nlitros/100 km",No,2025-02-17 19:38:08.024708,ref15440616
79,PEUGEOT 408 1.6 PHEV 133KW GT E-AUTO 181 5P,06/2023,Toledo,50 km,Eléctrico,0 EMISIONES,24 meses,Automático,Berlina mediana o grande,NaN,181 cv,5 Puertas,GRIS PLATINUM,38.300 €,BONILLA MOTOR\nProfesional,NaN,No,2025-02-17 19:38:16.024757,ref15238745

In [433]:
df["consumo_medio"].value_counts()

consumo_medio
Consumo medio\n0,00\nlitros/100 km    29
Consumo medio\nlitros/100 km           4
Consumo medio\n5,50\nlitros/100 km     3
Consumo medio\n4,90\nlitros/100 km     3
Consumo medio\n5,80\nlitros/100 km     3
Consumo medio\n4,60\nlitros/100 km     2
Consumo medio\n5,40\nlitros/100 km     2
Consumo medio\n4,30\nlitros/100 km     2
Consumo medio\n4,80\nlitros/100 km     2
Consumo medio\n6,10\nlitros/100 km     1
Consumo medio\n4,00\nlitros/100 km     1
Consumo medio\n3,70\nlitros/100 km     1
Consumo medio\n4,20\nlitros/100 km     1
Consumo medio\n4,70\nlitros/100 km     1
Consumo medio\n7,00\nlitros/100 km     1
Consumo medio\n5,00\nlitros/100 km     1
Consumo medio\n3,20\nlitros/100 km     1
Consumo medio\n3,80\nlitros/100 km     1
Consumo medio\n1,40\nlitros/100 km     1
Consumo medio\n5,70\nlitros/100 km     1
Consumo medio\n4,50\nlitros/100 km     1
Name: count, dtype: int64

In [434]:
df["consumo_medio"].isna().sum()

np.int64(18)

In [435]:
# campo nuevo marca_sola

df['marca_sola'] = df['marca'].apply(lambda x: x.split()[0] if isinstance(x, str) else x)

In [436]:
# renombrar "marca" por "modelo_titulo" y quitar marca

df.rename(columns={'marca': 'modelo_titulo'}, inplace=True)
df['modelo_titulo'] = df['modelo_titulo'].apply(lambda x: ' '.join(x.split()[1:]) if isinstance(x, str) else x)

In [437]:
df

,modelo_titulo,anio,localizacion,kilometraje,combustible,distintivo_ambiental,garantia,cambio,carroceria,plazas,potencia,puertas,color,precio,vendedor,consumo_medio,certificado,fecha_extraccion,referencia,marca_sola
0,308 SW 1.5 BlueHDi S&S Allure 130,01/2021,Sevilla,156.000 km,Diesel,C,12 meses,Manual,Stationwagon,5 asientos,130 cv,5 Puertas,Blanco / Metalizado,11.990 €,MOTOR CLUB SEVILLA\nProfesional,"Consumo medio\n0,00\nlitros/100 km",No,2025-02-17 19:26:27.595606,ref15276957,PEUGEOT
1,XC60 B4 R-Design AWD Aut.,01/2021,Sevilla,95.000 km,Diesel,ECO,12 meses,Automático,Todo Terreno,5 asientos,197 cv,5 Puertas,Azul / Metalizado,39.990 €,MOTOR CLUB SEVILLA\nProfesional,"Consumo medio\n5,50\nlitros/100 km",No,2025-02-17 19:26:35.003246,ref15168174,VOLVO
2,Rifter 1.5BlueHDi S&S Long Active Pack 130,09/2020,Almería,115.000 km,Diesel,C,12 meses,Manual,Monovolumen,5 asientos,131 cv,5 Puertas,Negro,18.500 €,AUTOMERCURY\nProfesional,"Consumo medio\n4,30\nlitros/100 km",No,2025-02-17 19:26:44.036638,ref13903932,PEUGEOT
3,Sportage Todoterreno 136cv Automático de 4 Pue...,10/2023,Valencia,21.470 km,NaN,NaN,12 meses,Automático,"4x4, SUV o pickup",NaN,136 cv,4 Puertas,PLATA,31.460 €,LEASING AUTOMOBILE\nProfesional,NaN,No,2025-02-17 19:26:52.390413,ref15317252,KIA
4,Q8 s-line,08/2023,Valencia,17.290 km,Diésel,NaN,12 meses,Automático,"4x4, SUV o pickup",NaN,286 cv,4 Puertas,BLANCO,72.274 €,LEASING AUTOMOBILE\nProfesional,NaN,No,2025-02-17 19:27:07.527248,ref15218308,AUDI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,Tarraco 1.5 TSI S&S Style 150,09/2019,Almería,71.800 km,Gasolina,C,24 meses,Manual,Todo Terreno,5 asientos,150 cv,5 Puertas,Gris,23.900 €,INDALO MOTOR Concesionario Oficial SEAT\nProfe...,"Consumo medio\n5,80\nlitros/100 km",No,2025-02-17 19:37:41.617133,ref15066087,SEAT
76,Captur TCe Techno 67kW,03/2024,Madrid,18.426 km,Gasolina,C,12 meses,Manual,Todo Terreno,5 asientos,90 cv,5 Puertas,Gris / Metalizado,21.290 €\n6%\n19.990 €,CLICARS MADRID\nProfesional,"Consumo medio\n0,00\nlitros/100 km",No,2025-02-17 19:37:49.595653,ref15390517,RENAULT
77,Formentor 1.5 TSI 150 DSG,06/2024,Almería,3.000 km,Gasolina,C,36 meses,Automático,Todo Terreno,5 asientos,150 cv,5 Puertas,Blanco,29.000 €,INDALO MOTOR Concesionario Oficial SEAT\nProfe...,"Consumo medio\n5,50\nlitros/100 km",No,2025-02-17 19:37:59.121730,ref15063293,CUPRA
78,Puma 1.0 EcoBoost ST-Line X 125,02/2020,Albacete,35.700 km,Gasolina,C,12 meses,Manual,Todo Terreno,5 asientos,125 cv,5 Puertas,Rojo,19.900 €,AUTOMOVILES GARRIDO\nProfesional,"Consumo medio\n4,50\nlitros/100 km",No,2025-02-17 19:38:08.024708,ref15440616,FORD
79,408 1.6 PHEV 133KW GT E-AUTO 181 5P,06/2023,Toledo,50 km,Eléctrico,0 EMISIONES,24 meses,Automático,Berlina mediana o grande,NaN,181 cv,5 Puertas,GRIS PLATINUM,38.300 €,BONILLA MOTOR\nProfesional,NaN,No,2025-02-17 19:38:16.024757,ref15238745,PEUGEOT

In [438]:
# sacar mes y año en columnas separadas

df[['mes_matricula', 'anio_matricula']] = df['anio'].str.split('/', expand=True)

df['mes_matricula'] = df['mes_matricula'].astype(int)
df['anio_matricula'] = df['anio_matricula'].astype(int)

df.drop(columns=["anio"], inplace=True)

In [439]:
def limpiar_kilometraje(valor):
    valor_limpio = valor.replace(".","").replace(" km","")
    return int(valor_limpio)

In [440]:
df["kilometraje"] = df["kilometraje"].apply(lambda x: limpiar_kilometraje(x) if isinstance(x, str) else np.nan)

In [441]:
df["garantia"].unique()

array(['12 meses', 'No', '18 meses', '24 meses', '60 meses', '36 meses'],
      dtype=object)

In [442]:
df[df["garantia"] == " meses"]["vendedor"].unique()

array([], dtype=object)

In [443]:
df["garantia"] = df["garantia"].replace("No", 0)
df["garantia"] = df["garantia"].replace("Sí", np.nan)
df["garantia"] = pd.to_numeric(df["garantia"].str.replace(" meses", ""), errors='coerce')

In [444]:
df.head(10)

,modelo_titulo,localizacion,kilometraje,combustible,distintivo_ambiental,garantia,cambio,carroceria,plazas,potencia,...,color,precio,vendedor,consumo_medio,certificado,fecha_extraccion,referencia,marca_sola,mes_matricula,anio_matricula
0,308 SW 1.5 BlueHDi S&S Allure 130,Sevilla,156000,Diesel,C,12.0,Manual,Stationwagon,5 asientos,130 cv,...,Blanco / Metalizado,11.990 €,MOTOR CLUB SEVILLA\nProfesional,"Consumo medio\n0,00\nlitros/100 km",No,2025-02-17 19:26:27.595606,ref15276957,PEUGEOT,1,2021
1,XC60 B4 R-Design AWD Aut.,Sevilla,95000,Diesel,ECO,12.0,Automático,Todo Terreno,5 asientos,197 cv,...,Azul / Metalizado,39.990 €,MOTOR CLUB SEVILLA\nProfesional,"Consumo medio\n5,50\nlitros/100 km",No,2025-02-17 19:26:35.003246,ref15168174,VOLVO,1,2021
2,Rifter 1.5BlueHDi S&S Long Active Pack 130,Almería,115000,Diesel,C,12.0,Manual,Monovolumen,5 asientos,131 cv,...,Negro,18.500 €,AUTOMERCURY\nProfesional,"Consumo medio\n4,30\nlitros/100 km",No,2025-02-17 19:26:44.036638,ref13903932,PEUGEOT,9,2020
3,Sportage Todoterreno 136cv Automático de 4 Pue...,Valencia,21470,NaN,NaN,12.0,Automático,"4x4, SUV o pickup",NaN,136 cv,...,PLATA,31.460 €,LEASING AUTOMOBILE\nProfesional,NaN,No,2025-02-17 19:26:52.390413,ref15317252,KIA,10,2023
4,Q8 s-line,Valencia,17290,Diésel,NaN,12.0,Automático,"4x4, SUV o pickup",NaN,286 cv,...,BLANCO,72.274 €,LEASING AUTOMOBILE\nProfesional,NaN,No,2025-02-17 19:27:07.527248,ref15218308,AUDI,8,2023
5,Serie 7 740 m-sport,Valencia,42573,Diésel,NaN,12.0,Automático,"4x4, SUV o pickup",NaN,340 cv,...,NEGRO,72.040 €,LEASING AUTOMOBILE\nProfesional,NaN,No,2025-02-17 19:27:16.169545,ref15218306,BMW,1,2022
6,500 1.0 Hybrid Dolcevita 52kW,Málaga,52446,Gasolina,ECO,12.0,Manual,Berlina,4 asientos,70 cv,...,Blanco / Metalizado,11.900 €,LAS CLARAS AUTOMOCION\nProfesional,"Consumo medio\n0,00\nlitros/100 km",No,2025-02-17 19:27:25.459010,ref15403473,FIAT,5,2022
7,X3 Todoterreno 190cv Automático de 4 Puertas,Valencia,112899,Diésel,NaN,12.0,Automático,"4x4, SUV o pickup",NaN,190 cv,...,BLANCO,28.887 €,LEASING AUTOMOBILE\nProfesional,NaN,No,2025-02-17 19:27:34.651727,ref15218305,BMW,10,2019
8,Serie 5 520dA M Sport,Valencia,65750,Diesel,ECO,12.0,Automático,Berlina,5 asientos,197 cv,...,NEGRO,35.674 €,LEASING AUTOMOBILE\nProfesional,"Consumo medio\n0,00\nlitros/100 km",No,2025-02-17 19:27:41.299602,ref15218300,BMW,12,2020
9,Berlingo M1 BlueHDi S&S Talla M Feel 100,Almería,97600,Diesel,C,12.0,Manual,Monovolumen,5 asientos,100 cv,...,Negro,17.900 €,AUTOMERCURY\nProfesional,"Consumo medio\n4,00\nlitros/100 km",No,2025-02-17 19:27:49.677432,ref12163959,CITROEN,6,2019

In [445]:
media_garantia = pd.to_numeric(round(df["garantia"].mean(), 0))
df['garantia'] = df["garantia"].fillna(media_garantia)

In [446]:
df["consumo_medio"].unique()

array(['Consumo medio\n0,00\nlitros/100 km',
       'Consumo medio\n5,50\nlitros/100 km',
       'Consumo medio\n4,30\nlitros/100 km', nan,
       'Consumo medio\n4,00\nlitros/100 km',
       'Consumo medio\n6,10\nlitros/100 km',
       'Consumo medio\n4,80\nlitros/100 km',
       'Consumo medio\n4,20\nlitros/100 km',
       'Consumo medio\n5,00\nlitros/100 km',
       'Consumo medio\n3,70\nlitros/100 km',
       'Consumo medio\n4,90\nlitros/100 km',
       'Consumo medio\n7,00\nlitros/100 km',
       'Consumo medio\n4,70\nlitros/100 km',
       'Consumo medio\n4,60\nlitros/100 km',
       'Consumo medio\n3,20\nlitros/100 km',
       'Consumo medio\n1,40\nlitros/100 km',
       'Consumo medio\n3,80\nlitros/100 km',
       'Consumo medio\nlitros/100 km',
       'Consumo medio\n5,80\nlitros/100 km',
       'Consumo medio\n5,70\nlitros/100 km',
       'Consumo medio\n5,40\nlitros/100 km',
       'Consumo medio\n4,50\nlitros/100 km'], dtype=object)

In [ ]:
# convertir a nan los que contengan \nlitros
# sustituir valor por solo lo que hay entre medio\n y \nlitros convertido a float redondeado a 2
# sustituir nans por media (22,5% en muestra: hay que ver porcentaje total de nans y hablar con grupo)


#df['consumo_medio'] = df['consumo_medio'].replace(r'.*\\nlitros.*', np.nan, regex=True)

# Paso 2: Sustituir el valor por solo lo que hay entre "medio\n" y "\nlitros" convertido a float redondeado a 2 decimales
#df['consumo_medio'] = df['consumo_medio'].apply(lambda x: float(re.search(r'medio\n(.*?)\nlitros', x).group(1)) if isinstance(x, str) and re.search(r'medio\n(.*?)\nlitros', x) else x)

# Paso 3: Sustituir NaNs por la media de la columna
#mean_value = df['consumo_medio'].mean()
# df['consumo_medio'] = df['consumo_medio'].fillna(mean_value)

In [448]:
df

,modelo_titulo,localizacion,kilometraje,combustible,distintivo_ambiental,garantia,cambio,carroceria,plazas,potencia,...,color,precio,vendedor,consumo_medio,certificado,fecha_extraccion,referencia,marca_sola,mes_matricula,anio_matricula
0,308 SW 1.5 BlueHDi S&S Allure 130,Sevilla,156000,Diesel,C,12.0,Manual,Stationwagon,5 asientos,130 cv,...,Blanco / Metalizado,11.990 €,MOTOR CLUB SEVILLA\nProfesional,"Consumo medio\n0,00\nlitros/100 km",No,2025-02-17 19:26:27.595606,ref15276957,PEUGEOT,1,2021
1,XC60 B4 R-Design AWD Aut.,Sevilla,95000,Diesel,ECO,12.0,Automático,Todo Terreno,5 asientos,197 cv,...,Azul / Metalizado,39.990 €,MOTOR CLUB SEVILLA\nProfesional,"Consumo medio\n5,50\nlitros/100 km",No,2025-02-17 19:26:35.003246,ref15168174,VOLVO,1,2021
2,Rifter 1.5BlueHDi S&S Long Active Pack 130,Almería,115000,Diesel,C,12.0,Manual,Monovolumen,5 asientos,131 cv,...,Negro,18.500 €,AUTOMERCURY\nProfesional,"Consumo medio\n4,30\nlitros/100 km",No,2025-02-17 19:26:44.036638,ref13903932,PEUGEOT,9,2020
3,Sportage Todoterreno 136cv Automático de 4 Pue...,Valencia,21470,NaN,NaN,12.0,Automático,"4x4, SUV o pickup",NaN,136 cv,...,PLATA,31.460 €,LEASING AUTOMOBILE\nProfesional,4.831034,No,2025-02-17 19:26:52.390413,ref15317252,KIA,10,2023
4,Q8 s-line,Valencia,17290,Diésel,NaN,12.0,Automático,"4x4, SUV o pickup",NaN,286 cv,...,BLANCO,72.274 €,LEASING AUTOMOBILE\nProfesional,4.831034,No,2025-02-17 19:27:07.527248,ref15218308,AUDI,8,2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,Tarraco 1.5 TSI S&S Style 150,Almería,71800,Gasolina,C,24.0,Manual,Todo Terreno,5 asientos,150 cv,...,Gris,23.900 €,INDALO MOTOR Concesionario Oficial SEAT\nProfe...,"Consumo medio\n5,80\nlitros/100 km",No,2025-02-17 19:37:41.617133,ref15066087,SEAT,9,2019
76,Captur TCe Techno 67kW,Madrid,18426,Gasolina,C,12.0,Manual,Todo Terreno,5 asientos,90 cv,...,Gris / Metalizado,21.290 €\n6%\n19.990 €,CLICARS MADRID\nProfesional,"Consumo medio\n0,00\nlitros/100 km",No,2025-02-17 19:37:49.595653,ref15390517,RENAULT,3,2024
77,Formentor 1.5 TSI 150 DSG,Almería,3000,Gasolina,C,36.0,Automático,Todo Terreno,5 asientos,150 cv,...,Blanco,29.000 €,INDALO MOTOR Concesionario Oficial SEAT\nProfe...,"Consumo medio\n5,50\nlitros/100 km",No,2025-02-17 19:37:59.121730,ref15063293,CUPRA,6,2024
78,Puma 1.0 EcoBoost ST-Line X 125,Albacete,35700,Gasolina,C,12.0,Manual,Todo Terreno,5 asientos,125 cv,...,Rojo,19.900 €,AUTOMOVILES GARRIDO\nProfesional,"Consumo medio\n4,50\nlitros/100 km",No,2025-02-17 19:38:08.024708,ref15440616,FORD,2,2020
79,408 1.6 PHEV 133KW GT E-AUTO 181 5P,Toledo,50,Eléctrico,0 EMISIONES,24.0,Automático,Berlina mediana o grande,NaN,181 cv,...,GRIS PLATINUM,38.300 €,BONILLA MOTOR\nProfesional,4.831034,No,2025-02-17 19:38:16.024757,ref15238745,PEUGEOT,6,2023

In [449]:
df['referencia'] = pd.to_numeric(df['referencia'].str.replace('ref', ''), errors='coerce')

In [ ]:
df["nombre_vendedor_profesional"] = pd.Series(dtype="string")
mask = df['vendedor'].str.endswith('\nProfesional')
df.loc[mask, 'nombre_vendedor_profesional'] = df.loc[mask, 'vendedor'].str.split('\nProfesional').str[0]
df['vendedor'] = df['vendedor'].apply(lambda x: True if '\nProfesional' in x else False)
df.rename(columns={'vendedor':'vendedor_profesional'}, inplace=True)
df['vendedor_profesional'].astype(bool)

In [451]:
df['color']=df['color'].apply(lambda x: x.upper())

In [452]:
# Traducir al español los colores en inglés y alemán
# "plateado" va al saco de grises

df.loc[df["color"].str.contains("BLACK|SCHWARZ", regex=True), "color"] = "NEGRO"
df.loc[df["color"].str.contains("WHITE|WEISS", regex=True), "color"] = "BLANCO"
df.loc[df["color"].str.contains("RED|ROT", regex=True), "color"] = "ROJO"
df.loc[df["color"].str.contains("BLUE|BLAU", regex=True), "color"] = "AZUL"
df.loc[df["color"].str.contains("GRAY|GREY|GRAU|PLATEADO|SILVER", regex=True), "color"] = "GRIS"

In [453]:
df['color'] = df['color'].str.split().str[0]

In [454]:
colores = ["NEGRO", "BLANCO", "AZUL", "ROJO", "GRIS"]
df['color'] = df['color'].apply(lambda x: x if x in colores else 'OTROS')

In [455]:
df.drop(columns=["vendedor_profesional", "mes_matricula", "anio_matricula"])

,modelo_titulo,localizacion,kilometraje,combustible,distintivo_ambiental,garantia,cambio,carroceria,plazas,potencia,puertas,color,precio,vendedor,consumo_medio,certificado,fecha_extraccion,referencia,marca_sola
0,308 SW 1.5 BlueHDi S&S Allure 130,Sevilla,156000,Diesel,C,12.0,Manual,Stationwagon,5 asientos,130 cv,5 Puertas,BLANCO,11.990 €,Profesional,"Consumo medio\n0,00\nlitros/100 km",No,2025-02-17 19:26:27.595606,15276957,PEUGEOT
1,XC60 B4 R-Design AWD Aut.,Sevilla,95000,Diesel,ECO,12.0,Automático,Todo Terreno,5 asientos,197 cv,5 Puertas,AZUL,39.990 €,Profesional,"Consumo medio\n5,50\nlitros/100 km",No,2025-02-17 19:26:35.003246,15168174,VOLVO
2,Rifter 1.5BlueHDi S&S Long Active Pack 130,Almería,115000,Diesel,C,12.0,Manual,Monovolumen,5 asientos,131 cv,5 Puertas,NEGRO,18.500 €,Profesional,"Consumo medio\n4,30\nlitros/100 km",No,2025-02-17 19:26:44.036638,13903932,PEUGEOT
3,Sportage Todoterreno 136cv Automático de 4 Pue...,Valencia,21470,NaN,NaN,12.0,Automático,"4x4, SUV o pickup",NaN,136 cv,4 Puertas,OTROS,31.460 €,Profesional,4.831034,No,2025-02-17 19:26:52.390413,15317252,KIA
4,Q8 s-line,Valencia,17290,Diésel,NaN,12.0,Automático,"4x4, SUV o pickup",NaN,286 cv,4 Puertas,BLANCO,72.274 €,Profesional,4.831034,No,2025-02-17 19:27:07.527248,15218308,AUDI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,Tarraco 1.5 TSI S&S Style 150,Almería,71800,Gasolina,C,24.0,Manual,Todo Terreno,5 asientos,150 cv,5 Puertas,GRIS,23.900 €,Profesional,"Consumo medio\n5,80\nlitros/100 km",No,2025-02-17 19:37:41.617133,15066087,SEAT
76,Captur TCe Techno 67kW,Madrid,18426,Gasolina,C,12.0,Manual,Todo Terreno,5 asientos,90 cv,5 Puertas,GRIS,21.290 €\n6%\n19.990 €,Profesional,"Consumo medio\n0,00\nlitros/100 km",No,2025-02-17 19:37:49.595653,15390517,RENAULT
77,Formentor 1.5 TSI 150 DSG,Almería,3000,Gasolina,C,36.0,Automático,Todo Terreno,5 asientos,150 cv,5 Puertas,BLANCO,29.000 €,Profesional,"Consumo medio\n5,50\nlitros/100 km",No,2025-02-17 19:37:59.121730,15063293,CUPRA
78,Puma 1.0 EcoBoost ST-Line X 125,Albacete,35700,Gasolina,C,12.0,Manual,Todo Terreno,5 asientos,125 cv,5 Puertas,ROJO,19.900 €,Profesional,"Consumo medio\n4,50\nlitros/100 km",No,2025-02-17 19:38:08.024708,15440616,FORD
79,408 1.6 PHEV 133KW GT E-AUTO 181 5P,Toledo,50,Eléctrico,0 EMISIONES,24.0,Automático,Berlina mediana o grande,NaN,181 cv,5 Puertas,GRIS,38.300 €,Profesional,4.831034,No,2025-02-17 19:38:16.024757,15238745,PEUGEOT

In [456]:
df["carroceria"].unique()

array(['Stationwagon', 'Todo Terreno', 'Monovolumen', '4x4, SUV o pickup',
       'Berlina', 'Coupe', 'Pequeño', 'Berlina mediana o grande',
       'Familiar'], dtype=object)

In [457]:
df['carroceria'].value_counts()

carroceria
Todo Terreno                30
Berlina                     24
4x4, SUV o pickup           10
Berlina mediana o grande     5
Stationwagon                 3
Monovolumen                  3
Coupe                        3
Pequeño                      1
Familiar                     1
Name: count, dtype: int64

In [458]:
df["carroceria"] = df["carroceria"].replace("Berlina mediana o grande", "Berlina")

In [459]:
df['carroceria'].value_counts()

carroceria
Todo Terreno         30
Berlina              29
4x4, SUV o pickup    10
Stationwagon          3
Monovolumen           3
Coupe                 3
Pequeño               1
Familiar              1
Name: count, dtype: int64

In [460]:
df["carroceria"] = df["carroceria"].replace("Stationwagon", "Familiar")

In [461]:
df['carroceria'].value_counts()

carroceria
Todo Terreno         30
Berlina              29
4x4, SUV o pickup    10
Familiar              4
Monovolumen           3
Coupe                 3
Pequeño               1
Name: count, dtype: int64

In [462]:
df["plazas"] = pd.to_numeric(df["plazas"].str.replace(" asientos", ""), errors='coerce')

In [463]:
df.head(3)

,modelo_titulo,localizacion,kilometraje,combustible,distintivo_ambiental,garantia,cambio,carroceria,plazas,potencia,...,precio,vendedor,consumo_medio,certificado,fecha_extraccion,referencia,marca_sola,mes_matricula,anio_matricula,vendedor_profesional
0,308 SW 1.5 BlueHDi S&S Allure 130,Sevilla,156000,Diesel,C,12.0,Manual,Familiar,5.0,130 cv,...,11.990 €,Profesional,"Consumo medio\n0,00\nlitros/100 km",No,2025-02-17 19:26:27.595606,15276957,PEUGEOT,1,2021,MOTOR CLUB SEVILLA
1,XC60 B4 R-Design AWD Aut.,Sevilla,95000,Diesel,ECO,12.0,Automático,Todo Terreno,5.0,197 cv,...,39.990 €,Profesional,"Consumo medio\n5,50\nlitros/100 km",No,2025-02-17 19:26:35.003246,15168174,VOLVO,1,2021,MOTOR CLUB SEVILLA
2,Rifter 1.5BlueHDi S&S Long Active Pack 130,Almería,115000,Diesel,C,12.0,Manual,Monovolumen,5.0,131 cv,...,18.500 €,Profesional,"Consumo medio\n4,30\nlitros/100 km",No,2025-02-17 19:26:44.036638,13903932,PEUGEOT,9,2020,AUTOMERCURY

In [464]:
df["puertas"] = pd.to_numeric(df["puertas"].str.replace(" Puertas", ""), errors='coerce')

In [465]:
df.drop(columns=["vendedor_profesional", "mes_matricula", "anio_matricula"])

,modelo_titulo,localizacion,kilometraje,combustible,distintivo_ambiental,garantia,cambio,carroceria,plazas,potencia,puertas,color,precio,vendedor,consumo_medio,certificado,fecha_extraccion,referencia,marca_sola
0,308 SW 1.5 BlueHDi S&S Allure 130,Sevilla,156000,Diesel,C,12.0,Manual,Familiar,5.0,130 cv,5,BLANCO,11.990 €,Profesional,"Consumo medio\n0,00\nlitros/100 km",No,2025-02-17 19:26:27.595606,15276957,PEUGEOT
1,XC60 B4 R-Design AWD Aut.,Sevilla,95000,Diesel,ECO,12.0,Automático,Todo Terreno,5.0,197 cv,5,AZUL,39.990 €,Profesional,"Consumo medio\n5,50\nlitros/100 km",No,2025-02-17 19:26:35.003246,15168174,VOLVO
2,Rifter 1.5BlueHDi S&S Long Active Pack 130,Almería,115000,Diesel,C,12.0,Manual,Monovolumen,5.0,131 cv,5,NEGRO,18.500 €,Profesional,"Consumo medio\n4,30\nlitros/100 km",No,2025-02-17 19:26:44.036638,13903932,PEUGEOT
3,Sportage Todoterreno 136cv Automático de 4 Pue...,Valencia,21470,NaN,NaN,12.0,Automático,"4x4, SUV o pickup",NaN,136 cv,4,OTROS,31.460 €,Profesional,4.831034,No,2025-02-17 19:26:52.390413,15317252,KIA
4,Q8 s-line,Valencia,17290,Diésel,NaN,12.0,Automático,"4x4, SUV o pickup",NaN,286 cv,4,BLANCO,72.274 €,Profesional,4.831034,No,2025-02-17 19:27:07.527248,15218308,AUDI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,Tarraco 1.5 TSI S&S Style 150,Almería,71800,Gasolina,C,24.0,Manual,Todo Terreno,5.0,150 cv,5,GRIS,23.900 €,Profesional,"Consumo medio\n5,80\nlitros/100 km",No,2025-02-17 19:37:41.617133,15066087,SEAT
76,Captur TCe Techno 67kW,Madrid,18426,Gasolina,C,12.0,Manual,Todo Terreno,5.0,90 cv,5,GRIS,21.290 €\n6%\n19.990 €,Profesional,"Consumo medio\n0,00\nlitros/100 km",No,2025-02-17 19:37:49.595653,15390517,RENAULT
77,Formentor 1.5 TSI 150 DSG,Almería,3000,Gasolina,C,36.0,Automático,Todo Terreno,5.0,150 cv,5,BLANCO,29.000 €,Profesional,"Consumo medio\n5,50\nlitros/100 km",No,2025-02-17 19:37:59.121730,15063293,CUPRA
78,Puma 1.0 EcoBoost ST-Line X 125,Albacete,35700,Gasolina,C,12.0,Manual,Todo Terreno,5.0,125 cv,5,ROJO,19.900 €,Profesional,"Consumo medio\n4,50\nlitros/100 km",No,2025-02-17 19:38:08.024708,15440616,FORD
79,408 1.6 PHEV 133KW GT E-AUTO 181 5P,Toledo,50,Eléctrico,0 EMISIONES,24.0,Automático,Berlina,NaN,181 cv,5,GRIS,38.300 €,Profesional,4.831034,No,2025-02-17 19:38:16.024757,15238745,PEUGEOT

In [466]:
# Paso 1: Sustituir por NaN los valores que contengan "medio\n0,00\nlitros" o "medio\nlitros"
df['consumo_medio'] = df['consumo_medio'].replace(
    [r'.*medio\n0,00\nlitros.*', r'.*medio\nlitros.*'], np.nan, regex=True)

# Paso 2: Dejar solo el número entre "medio\n" y "\nlitros" y convertir a float redondeado a 2 decimales
df['consumo_medio'] = df['consumo_medio'].str.extract(r'medio\n(.*?)\nlitros')[0]
df['consumo_medio'] = df['consumo_medio'].str.replace(',', '.').astype(float).round(2)

# mean_value = df['consumo_medio'].mean().round(2)
# df['consumo_medio'].fillna(mean_value, inplace=True)

In [467]:
df.drop(columns=["vendedor_profesional", "mes_matricula", "anio_matricula"])

,modelo_titulo,localizacion,kilometraje,combustible,distintivo_ambiental,garantia,cambio,carroceria,plazas,potencia,puertas,color,precio,vendedor,consumo_medio,certificado,fecha_extraccion,referencia,marca_sola
0,308 SW 1.5 BlueHDi S&S Allure 130,Sevilla,156000,Diesel,C,12.0,Manual,Familiar,5.0,130 cv,5,BLANCO,11.990 €,Profesional,NaN,No,2025-02-17 19:26:27.595606,15276957,PEUGEOT
1,XC60 B4 R-Design AWD Aut.,Sevilla,95000,Diesel,ECO,12.0,Automático,Todo Terreno,5.0,197 cv,5,AZUL,39.990 €,Profesional,5.5,No,2025-02-17 19:26:35.003246,15168174,VOLVO
2,Rifter 1.5BlueHDi S&S Long Active Pack 130,Almería,115000,Diesel,C,12.0,Manual,Monovolumen,5.0,131 cv,5,NEGRO,18.500 €,Profesional,4.3,No,2025-02-17 19:26:44.036638,13903932,PEUGEOT
3,Sportage Todoterreno 136cv Automático de 4 Pue...,Valencia,21470,NaN,NaN,12.0,Automático,"4x4, SUV o pickup",NaN,136 cv,4,OTROS,31.460 €,Profesional,NaN,No,2025-02-17 19:26:52.390413,15317252,KIA
4,Q8 s-line,Valencia,17290,Diésel,NaN,12.0,Automático,"4x4, SUV o pickup",NaN,286 cv,4,BLANCO,72.274 €,Profesional,NaN,No,2025-02-17 19:27:07.527248,15218308,AUDI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,Tarraco 1.5 TSI S&S Style 150,Almería,71800,Gasolina,C,24.0,Manual,Todo Terreno,5.0,150 cv,5,GRIS,23.900 €,Profesional,5.8,No,2025-02-17 19:37:41.617133,15066087,SEAT
76,Captur TCe Techno 67kW,Madrid,18426,Gasolina,C,12.0,Manual,Todo Terreno,5.0,90 cv,5,GRIS,21.290 €\n6%\n19.990 €,Profesional,NaN,No,2025-02-17 19:37:49.595653,15390517,RENAULT
77,Formentor 1.5 TSI 150 DSG,Almería,3000,Gasolina,C,36.0,Automático,Todo Terreno,5.0,150 cv,5,BLANCO,29.000 €,Profesional,5.5,No,2025-02-17 19:37:59.121730,15063293,CUPRA
78,Puma 1.0 EcoBoost ST-Line X 125,Albacete,35700,Gasolina,C,12.0,Manual,Todo Terreno,5.0,125 cv,5,ROJO,19.900 €,Profesional,4.5,No,2025-02-17 19:38:08.024708,15440616,FORD
79,408 1.6 PHEV 133KW GT E-AUTO 181 5P,Toledo,50,Eléctrico,0 EMISIONES,24.0,Automático,Berlina,NaN,181 cv,5,GRIS,38.300 €,Profesional,NaN,No,2025-02-17 19:38:16.024757,15238745,PEUGEOT

In [468]:
df["consumo_medio"].value_counts()

consumo_medio
5.5    3
5.8    3
4.9    3
5.4    2
4.3    2
4.6    2
4.8    2
4.0    1
5.0    1
4.2    1
6.1    1
4.7    1
7.0    1
3.7    1
3.2    1
3.8    1
1.4    1
5.7    1
4.5    1
Name: count, dtype: int64

In [469]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   modelo_titulo         80 non-null     object
 1   localizacion          80 non-null     object
 2   kilometraje           80 non-null     int64
 3   combustible           79 non-null     object
 4   distintivo_ambiental  71 non-null     object
 5   garantia              80 non-null     float64
 6   cambio                80 non-null     object
 7   carroceria            80 non-null     object
 8   plazas                64 non-null     float64
 9   potencia              80 non-null     object
 10  puertas               80 non-null     int64
 11  color                 80 non-null     object
 12  precio                80 non-null     object
 13  vendedor              80 non-null     object
 14  consumo_medio         29 non-null     float64
 15  certificado           80 non-null     object
 16  fecha_extraccion      80 non-null     object
 17  referencia            80 non-null     int64
 18  marca_sola            80 non-null     object
 19  mes_matricula         80 non-null     int64
 20  anio_matricula        80 non-null     int64
 21  vendedor_profesional  80 non-null     string
dtypes: float64(3), int64(5), object(13), string(1)
memory usage: 13.9+ KB

In [470]:
df["precio"].unique()

array(['11.990 €', '39.990 €', '18.500 €', '31.460 €', '72.274 €',
       '72.040 €', '11.900 €', '28.887 €', '35.674 €', '17.900 €',
       '49.894 €', '73.687 €', '28.654 €', '30.483 €', '7.000 €',
       '38.729 €', '39.900 €', '23.990 €', '44.900 €', '43.900 €',
       '21.900 €', '79.300 €\n6%\n74.300 €', '28.900 €', '25.950 €',
       '16.900 €', '34.900 €', '38.850 €', '19.500 €', '54.900 €',
       '14.500 €', '9.990 €', '14.990 €', '30.900 €', '33.900 €',
       '9.490 €', '26.500 €', '18.900 €', '24.990 €', '27.900 €',
       '41.900 €', '9.900 €', '29.900 €', '35.900 €', '19.300 €',
       '20.900 €', '42.000 €', '20.500 €', '38.500 €', '45.900 €',
       '20.990 €', '46.900 €', '15.500 €', '19.990 €', '44.990 €',
       '23.500 €', '13.990 €', '24.500 €', '10.990 €', '17.500 €',
       '25.490 €', '21.500 €', '13.990 €\n4%\n13.490 €', '23.900 €',
       '21.290 €\n6%\n19.990 €', '29.000 €', '19.900 €', '38.300 €'],
      dtype=object)

In [ ]:
df['precio'] = df['precio'].str.replace('.', '').str.replace(' €', '')
df['precio'] = df['precio'].str.split('\n').str[0]
df['precio'] = pd.to_numeric(df['precio'], errors='coerce')

In [473]:
df["cambio"].unique()

array(['Manual', 'Automático'], dtype=object)

In [474]:
df.drop(columns=["vendedor_profesional", "mes_matricula", "anio_matricula"])

,modelo_titulo,localizacion,kilometraje,combustible,distintivo_ambiental,garantia,cambio,carroceria,plazas,potencia,puertas,color,precio,vendedor,consumo_medio,certificado,fecha_extraccion,referencia,marca_sola
0,308 SW 1.5 BlueHDi S&S Allure 130,Sevilla,156000,Diesel,C,12.0,Manual,Familiar,5.0,130 cv,5,BLANCO,11990,Profesional,NaN,No,2025-02-17 19:26:27.595606,15276957,PEUGEOT
1,XC60 B4 R-Design AWD Aut.,Sevilla,95000,Diesel,ECO,12.0,Automático,Todo Terreno,5.0,197 cv,5,AZUL,39990,Profesional,5.5,No,2025-02-17 19:26:35.003246,15168174,VOLVO
2,Rifter 1.5BlueHDi S&S Long Active Pack 130,Almería,115000,Diesel,C,12.0,Manual,Monovolumen,5.0,131 cv,5,NEGRO,18500,Profesional,4.3,No,2025-02-17 19:26:44.036638,13903932,PEUGEOT
3,Sportage Todoterreno 136cv Automático de 4 Pue...,Valencia,21470,NaN,NaN,12.0,Automático,"4x4, SUV o pickup",NaN,136 cv,4,OTROS,31460,Profesional,NaN,No,2025-02-17 19:26:52.390413,15317252,KIA
4,Q8 s-line,Valencia,17290,Diésel,NaN,12.0,Automático,"4x4, SUV o pickup",NaN,286 cv,4,BLANCO,72274,Profesional,NaN,No,2025-02-17 19:27:07.527248,15218308,AUDI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,Tarraco 1.5 TSI S&S Style 150,Almería,71800,Gasolina,C,24.0,Manual,Todo Terreno,5.0,150 cv,5,GRIS,23900,Profesional,5.8,No,2025-02-17 19:37:41.617133,15066087,SEAT
76,Captur TCe Techno 67kW,Madrid,18426,Gasolina,C,12.0,Manual,Todo Terreno,5.0,90 cv,5,GRIS,21290,Profesional,NaN,No,2025-02-17 19:37:49.595653,15390517,RENAULT
77,Formentor 1.5 TSI 150 DSG,Almería,3000,Gasolina,C,36.0,Automático,Todo Terreno,5.0,150 cv,5,BLANCO,29000,Profesional,5.5,No,2025-02-17 19:37:59.121730,15063293,CUPRA
78,Puma 1.0 EcoBoost ST-Line X 125,Albacete,35700,Gasolina,C,12.0,Manual,Todo Terreno,5.0,125 cv,5,ROJO,19900,Profesional,4.5,No,2025-02-17 19:38:08.024708,15440616,FORD
79,408 1.6 PHEV 133KW GT E-AUTO 181 5P,Toledo,50,Eléctrico,0 EMISIONES,24.0,Automático,Berlina,NaN,181 cv,5,GRIS,38300,Profesional,NaN,No,2025-02-17 19:38:16.024757,15238745,PEUGEOT

In [478]:
df["potencia"].unique()

array(['130 cv', '197 cv', '131 cv', '136 cv', '286 cv', '340 cv',
       '70 cv', '190 cv', '100 cv', '150 cv', '140 cv', '184 cv',
       '115 cv', '388 cv', '141 cv', '170 cv', '110 cv', '313 cv',
       '129 cv', '125 cv', '205 cv', '116 cv', '120 cv', '82 cv',
       '265 cv', '109 cv', '225 cv', '180 cv', '95 cv', '80 cv', '231 cv',
       '90 cv', '181 cv'], dtype=object)

In [479]:
df['potencia'] = df['potencia'].str.replace(' cv', '')
df['potencia'] = pd.to_numeric(df['potencia'], errors='coerce')

In [480]:
df.drop(columns=["vendedor_profesional", "mes_matricula", "anio_matricula"])

,modelo_titulo,localizacion,kilometraje,combustible,distintivo_ambiental,garantia,cambio,carroceria,plazas,potencia,puertas,color,precio,vendedor,consumo_medio,certificado,fecha_extraccion,referencia,marca_sola,peninsula_y_baleares
0,308 SW 1.5 BlueHDi S&S Allure 130,Sevilla,156000,Diesel,C,12.0,Manual,Familiar,5.0,130,5,BLANCO,11990,Profesional,NaN,No,2025-02-17 19:26:27.595606,15276957,PEUGEOT,True
1,XC60 B4 R-Design AWD Aut.,Sevilla,95000,Diesel,ECO,12.0,Automático,Todo Terreno,5.0,197,5,AZUL,39990,Profesional,5.5,No,2025-02-17 19:26:35.003246,15168174,VOLVO,True
2,Rifter 1.5BlueHDi S&S Long Active Pack 130,Almería,115000,Diesel,C,12.0,Manual,Monovolumen,5.0,131,5,NEGRO,18500,Profesional,4.3,No,2025-02-17 19:26:44.036638,13903932,PEUGEOT,True
3,Sportage Todoterreno 136cv Automático de 4 Pue...,Valencia,21470,NaN,NaN,12.0,Automático,"4x4, SUV o pickup",NaN,136,4,OTROS,31460,Profesional,NaN,No,2025-02-17 19:26:52.390413,15317252,KIA,True
4,Q8 s-line,Valencia,17290,Diésel,NaN,12.0,Automático,"4x4, SUV o pickup",NaN,286,4,BLANCO,72274,Profesional,NaN,No,2025-02-17 19:27:07.527248,15218308,AUDI,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,Tarraco 1.5 TSI S&S Style 150,Almería,71800,Gasolina,C,24.0,Manual,Todo Terreno,5.0,150,5,GRIS,23900,Profesional,5.8,No,2025-02-17 19:37:41.617133,15066087,SEAT,True
76,Captur TCe Techno 67kW,Madrid,18426,Gasolina,C,12.0,Manual,Todo Terreno,5.0,90,5,GRIS,21290,Profesional,NaN,No,2025-02-17 19:37:49.595653,15390517,RENAULT,True
77,Formentor 1.5 TSI 150 DSG,Almería,3000,Gasolina,C,36.0,Automático,Todo Terreno,5.0,150,5,BLANCO,29000,Profesional,5.5,No,2025-02-17 19:37:59.121730,15063293,CUPRA,True
78,Puma 1.0 EcoBoost ST-Line X 125,Albacete,35700,Gasolina,C,12.0,Manual,Todo Terreno,5.0,125,5,ROJO,19900,Profesional,4.5,No,2025-02-17 19:38:08.024708,15440616,FORD,True
79,408 1.6 PHEV 133KW GT E-AUTO 181 5P,Toledo,50,Eléctrico,0 EMISIONES,24.0,Automático,Berlina,NaN,181,5,GRIS,38300,Profesional,NaN,No,2025-02-17 19:38:16.024757,15238745,PEUGEOT,True

In [ ]:
fuera_de_peninsula_baleares = ["Tenerife", "Las Palmas", "Ceuta", "Melilla"]
df['peninsula_y_baleares'] = True
df.loc[df['localizacion'].isin(fuera_de_peninsula_baleares), 'peninsula_y_baleares'] = False

In [477]:
df.drop(columns=["vendedor_profesional", "mes_matricula", "anio_matricula"])

,modelo_titulo,localizacion,kilometraje,combustible,distintivo_ambiental,garantia,cambio,carroceria,plazas,potencia,puertas,color,precio,vendedor,consumo_medio,certificado,fecha_extraccion,referencia,marca_sola,peninsula_y_baleares
0,308 SW 1.5 BlueHDi S&S Allure 130,Sevilla,156000,Diesel,C,12.0,Manual,Familiar,5.0,130 cv,5,BLANCO,11990,Profesional,NaN,No,2025-02-17 19:26:27.595606,15276957,PEUGEOT,True
1,XC60 B4 R-Design AWD Aut.,Sevilla,95000,Diesel,ECO,12.0,Automático,Todo Terreno,5.0,197 cv,5,AZUL,39990,Profesional,5.5,No,2025-02-17 19:26:35.003246,15168174,VOLVO,True
2,Rifter 1.5BlueHDi S&S Long Active Pack 130,Almería,115000,Diesel,C,12.0,Manual,Monovolumen,5.0,131 cv,5,NEGRO,18500,Profesional,4.3,No,2025-02-17 19:26:44.036638,13903932,PEUGEOT,True
3,Sportage Todoterreno 136cv Automático de 4 Pue...,Valencia,21470,NaN,NaN,12.0,Automático,"4x4, SUV o pickup",NaN,136 cv,4,OTROS,31460,Profesional,NaN,No,2025-02-17 19:26:52.390413,15317252,KIA,True
4,Q8 s-line,Valencia,17290,Diésel,NaN,12.0,Automático,"4x4, SUV o pickup",NaN,286 cv,4,BLANCO,72274,Profesional,NaN,No,2025-02-17 19:27:07.527248,15218308,AUDI,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,Tarraco 1.5 TSI S&S Style 150,Almería,71800,Gasolina,C,24.0,Manual,Todo Terreno,5.0,150 cv,5,GRIS,23900,Profesional,5.8,No,2025-02-17 19:37:41.617133,15066087,SEAT,True
76,Captur TCe Techno 67kW,Madrid,18426,Gasolina,C,12.0,Manual,Todo Terreno,5.0,90 cv,5,GRIS,21290,Profesional,NaN,No,2025-02-17 19:37:49.595653,15390517,RENAULT,True
77,Formentor 1.5 TSI 150 DSG,Almería,3000,Gasolina,C,36.0,Automático,Todo Terreno,5.0,150 cv,5,BLANCO,29000,Profesional,5.5,No,2025-02-17 19:37:59.121730,15063293,CUPRA,True
78,Puma 1.0 EcoBoost ST-Line X 125,Albacete,35700,Gasolina,C,12.0,Manual,Todo Terreno,5.0,125 cv,5,ROJO,19900,Profesional,4.5,No,2025-02-17 19:38:08.024708,15440616,FORD,True
79,408 1.6 PHEV 133KW GT E-AUTO 181 5P,Toledo,50,Eléctrico,0 EMISIONES,24.0,Automático,Berlina,NaN,181 cv,5,GRIS,38300,Profesional,NaN,No,2025-02-17 19:38:16.024757,15238745,PEUGEOT,True

In [482]:
df["certificado"].unique()

array(['No', 'Si'], dtype=object)

In [483]:
df["certificado"] = df["certificado"].replace("No", False)
df["certificado"] = df["certificado"].replace("Sí", True)
df["certificado"] = df["certificado"].astype(bool)

In [486]:
df['fecha_extraccion'] = pd.to_datetime(df['fecha_extraccion'])

In [491]:
df.drop(columns=["vendedor_profesional", "mes_matricula", "anio_matricula"])

,modelo_titulo,localizacion,kilometraje,combustible,distintivo_ambiental,garantia,cambio_automatico,carroceria,plazas,potencia,puertas,color,precio,vendedor,consumo_medio,certificado,fecha_extraccion,referencia,marca_sola,peninsula_y_baleares
0,308 SW 1.5 BlueHDi S&S Allure 130,Sevilla,156000,Diesel,C,12.0,False,Familiar,5.0,130,5,BLANCO,11990,Profesional,NaN,False,2025-02-17 19:26:27.595606,15276957,PEUGEOT,True
1,XC60 B4 R-Design AWD Aut.,Sevilla,95000,Diesel,ECO,12.0,True,Todo Terreno,5.0,197,5,AZUL,39990,Profesional,5.5,False,2025-02-17 19:26:35.003246,15168174,VOLVO,True
2,Rifter 1.5BlueHDi S&S Long Active Pack 130,Almería,115000,Diesel,C,12.0,False,Monovolumen,5.0,131,5,NEGRO,18500,Profesional,4.3,False,2025-02-17 19:26:44.036638,13903932,PEUGEOT,True
3,Sportage Todoterreno 136cv Automático de 4 Pue...,Valencia,21470,NaN,NaN,12.0,True,"4x4, SUV o pickup",NaN,136,4,OTROS,31460,Profesional,NaN,False,2025-02-17 19:26:52.390413,15317252,KIA,True
4,Q8 s-line,Valencia,17290,Diésel,NaN,12.0,True,"4x4, SUV o pickup",NaN,286,4,BLANCO,72274,Profesional,NaN,False,2025-02-17 19:27:07.527248,15218308,AUDI,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,Tarraco 1.5 TSI S&S Style 150,Almería,71800,Gasolina,C,24.0,False,Todo Terreno,5.0,150,5,GRIS,23900,Profesional,5.8,False,2025-02-17 19:37:41.617133,15066087,SEAT,True
76,Captur TCe Techno 67kW,Madrid,18426,Gasolina,C,12.0,False,Todo Terreno,5.0,90,5,GRIS,21290,Profesional,NaN,False,2025-02-17 19:37:49.595653,15390517,RENAULT,True
77,Formentor 1.5 TSI 150 DSG,Almería,3000,Gasolina,C,36.0,True,Todo Terreno,5.0,150,5,BLANCO,29000,Profesional,5.5,False,2025-02-17 19:37:59.121730,15063293,CUPRA,True
78,Puma 1.0 EcoBoost ST-Line X 125,Albacete,35700,Gasolina,C,12.0,False,Todo Terreno,5.0,125,5,ROJO,19900,Profesional,4.5,False,2025-02-17 19:38:08.024708,15440616,FORD,True
79,408 1.6 PHEV 133KW GT E-AUTO 181 5P,Toledo,50,Eléctrico,0 EMISIONES,24.0,True,Berlina,NaN,181,5,GRIS,38300,Profesional,NaN,False,2025-02-17 19:38:16.024757,15238745,PEUGEOT,True

In [489]:
df.rename(columns={'cambio': 'cambio_automatico'}, inplace=True)
df['cambio_automatico'] = df['cambio_automatico'].apply(lambda x: True if x == 'Automático' else False)

In [487]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   modelo_titulo         80 non-null     object
 1   localizacion          80 non-null     object
 2   kilometraje           80 non-null     int64
 3   combustible           79 non-null     object
 4   distintivo_ambiental  71 non-null     object
 5   garantia              80 non-null     float64
 6   cambio                80 non-null     object
 7   carroceria            80 non-null     object
 8   plazas                64 non-null     float64
 9   potencia              80 non-null     int64
 10  puertas               80 non-null     int64
 11  color                 80 non-null     object
 12  precio                80 non-null     int64
 13  vendedor              80 non-null     object
 14  consumo_medio         29 non-null     float64
 15  certificado           80 non-null     bool
 16  fecha_extraccion      80 non-null     datetime64[ns]
 17  referencia            80 non-null     int64
 18  marca_sola            80 non-null     object
 19  mes_matricula         80 non-null     int64
 20  anio_matricula        80 non-null     int64
 21  vendedor_profesional  80 non-null     string
 22  peninsula_y_baleares  80 non-null     bool
dtypes: bool(2), datetime64[ns](1), float64(3), int64(7), object(9), string(1)
memory usage: 13.4+ KB